### ISSUE TITLE
Update Documents in the Index

### ISSUE THREAD

**Issue by jladbury** [nextapps-de/flexsearch#100]
First, many thanks for an excellent component!
I tried to update a single item in the index using code similar to that in the example:
```
index.update({
    data:{
        id: 0,
        title: "Foo",
        body: {
            content: "Bar"
        }
    }
});
```
(in my case, `.update({'data':evInChronology})`). 
This did not work.
On a hunch, I tried doing it using the same pattern as used for add and remove (`index.add/remove(docs)`), passing the item I wanted to update. - in my case `.update(evInChronology)`.
That worked fine. 
Am I missing something, or is this a documentation problem? I notice also that the text preceding the `index.update` example mentions an array, but the example does not include one.

**Comment by jladbury** [comment]
I have put up a jsbin that replicates the issue:
[https://jsbin.com/sogoqaw/5/edit?js,console](url)

**Comment by jladbury** [comment]
There is a similar issue with `remove`, which is shown in the bin [https://jsbin.com/sogoqaw/6/edit?js,console](url)

**Comment by MatteoBassan** [comment]
My **temporary** solution is to use find() on the id, and then pass the object found to remove(). This is the only way i found to remove an object...

**Comment by kristiandupont** [comment]
It seems that the documentation and the types are wrong? I changed my code using both `update` and `remove` from supplying an id (first) to supplying a "document" with the id inside, which seems to work. The weird thing is that looking into the source, this doesn't look like what should be the case. Is that because there is a mismatch to the published version?

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
