### ISSUE TITLE
What was the config of benchmarks?

### ISSUE THREAD

**Issue by agtabesh** [nextapps-de/flexsearch#101]
Hi there,
You have done a benchmark [here](https://github.com/nextapps-de/flexsearch#consumption). My question is which config did you use to accomplish that?

Thanks.

**Comment by ts-thomas** [comment]
Hello, the preset _memory_ was used for this test, which have these settings:

```js
{
    encode: "extra",
    tokenize: "strict",
    threshold: 0,
    resolution: 1
}
```
