### ISSUE TITLE
how to do a search for that matches all documents?

### ISSUE THREAD

**Issue by desjob** [nextapps-de/flexsearch#102]
When my user has entered an empty query string `''` i would like the `index.search()` api to return all results.
I have seen a way to do this using `index.where(() => true)`, however, i would like to use other features of the `.search()` api, like pagination, sorting and limit. 

Currently, i made a hacky workaround for this by adding an extra `{all: '1'} ` field to each of my documents, and when the user searches for '', i change the targeted field and value to that instead. Feels bad :(

**Comment by manuelportela** [comment]
I did something smelly as well, but maybe it stinks a little less.

1. I also added a field "all" with the contents of a const string "__ALL_TOKEN__" (actually a static string in my SearchEngine Class) to all documents
2. in a search I do flexSearch.search({query: q || SearchEngine.ALL_TOKEN})

I like it a little better than yours, but feel that this could be handled better

**Comment by eliranmal** [comment]
@desjob - that sounds like a noop; why not just bypass `FlexSearch` altogether when the term is empty?

**Comment by zlepper** [comment]
@eliranmal Because other filters might still apply, just not the query part specifically, so being able to exclude the query part specifically is a requirement for most.

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x which gives you access to the "store", thanks a lot.
