### ISSUE TITLE
how to set the search {sort} direction (ascending/descending)

### ISSUE THREAD

**Issue by desjob** [nextapps-de/flexsearch#103]
I am using the `{sort: 'field'}` option when using the `index.search(options)` API.
How can I set the sort direction (ascending/descending)?

**Comment by ts-thomas** [comment]
I just noticed that the sorting direction cannot be reversed actually through the config object.

There are 2 possibilities:

1. Adding a new field in the config object to define sorting order, e.g.:
`{sort: 'field', order: 'desc'}`

2. Support special chars in the existing field "sort" to switch ordering, e.g.:
`{sort: '>field'}`

What would you prefer? Or do you have another suggestion for this purpose?

**Comment by ts-thomas** [comment]
In the meanwhile you can use a custom sort: https://github.com/nextapps-de/flexsearch#custom-sort

**Comment by desjob** [comment]
I would prefer the `{sort: 'field', order: 'desc'}`
Or, alternatively, an extra "sortDirection" field on root level of the config object, which would be backwards compatible if it gets the current order (ascending) by default.

**Comment by desjob** [comment]
And thanks for your suggestion!

**Comment by desjob** [comment]
One thing I noticed about custom sorting is that it seems to be applied after the limit. So with a limit of 10, you would get the top 10 results based on score, but after that you sort those i.e. on date. However if you then show the second page it can lead to some unexpected results, because the dates don't start where the first page stopped.

Is the built in "sort" applied before the limit?

**Comment by ts-thomas** [comment]
You are right, the sort is applied after the limit. This may produce undesired effects. I have to find a way to apply sorting before the limit without rapidly increasing the complexity in calculations and memory. This could be done just before or at least during the intersection, but the enrichment is performing after this part and it is initially required to make a sort by a custom field. Applying the enrichment before the intersection on the other hand is maybe to complex and doesn't scale well.

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
