### ISSUE TITLE
Index size bigger than the orginal data

### ISSUE THREAD

**Issue by tareefdev** [nextapps-de/flexsearch#105]
Is it normal to get an index file which is larger (in size) than the original data file?

I have [JSON file](https://github.com/nextapps-de/flexsearch/files/3376732/data.zip) with ~ 1MB of size (about 58,278 words). When Trying to build an index for it using the following code:

```
const index_ar = new FlexSearch({
  tokenize: "strict",
  rtl: true,
  split: /\s+/,
  doc: {
    id: "id",
    field: [
      'title',
      'incident_date_time',
      'location:name'
    ]
  }
});
 index_ar.add(data);
```
The index file size is ~ 2.1MB! 
I inspected the file size using the following method:

```
const exportedIndex = index_ar.export();
fs.writeFileSync('exported.json', JSON.stringify(exportedIndex));
```

Is there any wrong in the code? or it's normal to get an index size bigger than original data?

**Comment by ts-thomas** [comment]
It may depends on your datatype of passed IDs. Could you provide me a short piece of data you have indexed?

**Comment by tareefdev** [comment]
I uploaded the data I need to index in my first comment here under the word "JSON file ".

**Comment by desjob** [comment]
I would say that it is expected that the index size is always larger as the original data, because the index will duplicate data to be able to search fast.

Think of it as adding a traditional index to an existing book: for each word that occurs in the book, you add a list on which pages it occurs. Now your book is several pages thicker!

**Comment by ts-thomas** [comment]
@tareefdev thanks a lot for the test data.

It may sounds weird, but it can happen as @desjob already pointed out. Generally the memory size will shrink when using your settings ("strict" tokenizer, non-contextual, split by words). There are also one or two features missing (it is work in progress actually) which lets you define fields to store as document and define fields to add to the index separately. Actually when performing an export, the export will include the index __plus__ the full original document. I will also add a parameter to the export function which lets you export just the index without the doc (but when importing, the doc has to be added from another source in this case).

**Comment by tareefdev** [comment]
@desjob thanks for the example!

@ts-thomas A great answer, thanks! Thus the doc needs to be updated to mention that:
- The index size would be almost as the data itself.
- The export function would also include a copy of the original document.
I wonder what is that parameter to export just the index? Or does it in progress?

I confused now which is the better choice for my use case. I'm building a site using Gatsby.js, **one page** needs to be a search page in the data I sent. Considering my index settings ("strict" tokenizer, non-contextual, split by words) and that I need to load the index file plus the original document, I wonder if it's better in such case to use React itself (Gatsby is a React framework) to load the data and search through it, so I would have the same results (performance?) with half of data transfer size?

**Comment by ts-thomas** [comment]
It is now supported by the new update in v0.6.24: https://github.com/nextapps-de/flexsearch#separate-exports-documents

**Comment by tareefdev** [comment]
This is a really nice option, thanks for the great work.

I want to emphasize again on that particular use case, when using very basic functionalities from FlexSearch; ("strict" tokenizer, non-contextual, split by words). In this case, I don't see any difference (in performance and data size) between:

- Building an index and load it with a copy of my data
- Just loading the data and then using a framework (React) to filter and display it.
 
What benefits of using FlexSearch here?
