### ISSUE TITLE
export/import without json serializing

### ISSUE THREAD

**Issue by desjob** [nextapps-de/flexsearch#110]
I would really like to export the index to IndexedDB. However, for that case there is no need to JSON serialize it, and it's costs quite some time to do so for a large index. while it's not needed.

I created a PR to make the JSON encoding/decoding on import/export optional, hope you will accept it!

**Comment by desjob** [comment]
see PR: https://github.com/nextapps-de/flexsearch/pull/111

**Comment by ts-thomas** [comment]
Please notice the new update in v0.6.24: https://github.com/nextapps-de/flexsearch#disable-serialization
