### ISSUE TITLE
How to make index the Arabic or Persian text?!

### ISSUE THREAD

**Issue by hamedsbt** [nextapps-de/flexsearch#112]
How to make index the Arabic or Persian text and full-text search through it ?!
I tried to add Encoding and Stemmer, but not success!

**Comment by ts-thomas** [comment]
https://github.com/nextapps-de/flexsearch#right-to-left-support
https://github.com/nextapps-de/flexsearch#cjk-word-break-chinese-japanese-korean

Does that help?

**Comment by hmmlsystems** [comment]
@ts-thomas Love flexsearch! Thank you and keep it up.

We're also seeing issues with indexing script languages like Arabic in our tests. The problem for us is that our index includes English text as well as Arabic. So your right to left suggesting wasn't working. 

If you want I can share our simple search page and data file. Thanks again.

**Comment by ts-thomas** [comment]
Thanks a lot. Please share a simple example so I can take a look on the data. Using different configs for each field may help.

**Comment by hmmlsystems** [comment]
Thanks! https://gist.github.com/hmmlsystems/9913b1af1d8b1207fb32285fa031a05a

**Comment by texzone** [comment]
As far as indexing arabic (and only arabic) text, the docs did not help. However, @ts-thomas reply in this threat [here](https://github.com/nextapps-de/flexsearch/issues/51#issuecomment-497655639) worked for me.

```
var index = FlexSearch.create({
    encode: false,
    rtl: true,
    split: /\s+/,
    tokenize: "forward"
});
```

**Comment by elbadwihi** [comment]
> As far as indexing arabic (and only arabic) text, the docs did not help. However, @ts-thomas reply in this threat [here](https://github.com/nextapps-de/flexsearch/issues/51#issuecomment-497655639) worked for me.
> 
> ```
> var index = FlexSearch.create({
>     encode: false,
>     rtl: true,
>     split: /\s+/,
>     tokenize: "forward"
> });
> ```

I've tried the above, and many other options, but it doesn't work for me. Any tips? I need to show both English and Arabic results, but I can't get Arabic to show at all, even on its own.
