### ISSUE TITLE
Nested array ?

### ISSUE THREAD

**Issue by gotenxds** [nextapps-de/flexsearch#113]
Hello, I have the following doc array:

`
[
  { 
     title: "title",
     content: [
         {
              title: "title2",
              text: "Alot of text"
         },
..
..
..
     ]
  }
]
`

The Complex object section in the readme states to use a colon for nested fields, but this does not seem to work for arrays.
Any way of doing this ?

I need to be able to search for all fields, so in `title, nested title, text`

**Comment by NiketBajaj** [comment]
I am facing same issue, do we have any solution on it ? or workaround for now ?

**Comment by ts-thomas** [comment]
The upcoming version 0.7.0 can handle nested arrays, then you could define:
```js
doc: {
    id: "id",
    field: [
        "title",
        "content[]:title",
        "content[]:text"
    ]
}
```

Also mapping would be supported, e.g.:
```js
doc: {
    id: "id",
    field: {
        "main": "title",
        "title": "content[]:title",
        "text": "content[]:text"
    }
}
```

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
