### ISSUE TITLE
Merging indices

### ISSUE THREAD

**Issue by Arogova** [nextapps-de/flexsearch#114]
Hi,
I need to import/export a huge index (at least 100k items of several paragraphs each). 
Right now, when trying to import more than about 40k, JSON.parse throws the "invalid string length" error. 
I have implemented [msgpack](https://msgpack.org/) as a replacement for JSON.stringify and JSON.parse but the limit is still too low. 
The easiest solution would probably be to cut the index into several smaller indices and import them one after the other but that requires the import function to add to the index as opposed to replacing it, as it does now. 
Do you think that's possible or should I look into another solution (streaming the exported file and building the JSON object bit by bit maybe) ?

**Comment by ts-thomas** [comment]
That issue is in the top section of my todo list. A solution will come very soon.

**Comment by wbelk** [comment]
@ts-thomas Piggybacking on this question. Would there be any issue in the client to import multiple indexes sequentially (provided they are pre-compiled with the same index options)?

E.g. the client loads a gzipped index and import(), then later based on some event, another pre-compiled index is requested via gzip and import(). Are those two indexes then combined without issue? Effectively, acting as a backfill when paginated results are running low.

Would the pagination also be able to continue without issue in the above scenario (provided that `limit, page` are respected)?

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
