### ISSUE TITLE
How to use with React & Redux?

### ISSUE THREAD

**Issue by johnli611** [nextapps-de/flexsearch#116]
Hi!

First off, great library and documentation =)

I'm using FlexSearch with React and want to store the index in my Redux store to access across my browser app. It works the first time when I instantiate the index, but all the functions (index.search, index.add, etc.) stop working when I pull it from the store to use, despite the index being successfully stored. I dug in a bit deeper and it seems like the functions aren't part of the index anymore. I'm not sure what's going on.

**Here's a successful query the first time I use it.**

<img width="350" alt="Screen Shot 2019-08-03 at 11 40 02 AM" src="https://user-images.githubusercontent.com/15110789/62410235-7b290400-b5e3-11e9-9677-76bf6a8e0d54.png">

**Here's the error every subsequent time after. As you can see, the search function isn't there anymore.**

<img width="711" alt="Screen Shot 2019-08-03 at 11 41 38 AM" src="https://user-images.githubusercontent.com/15110789/62410250-b7f4fb00-b5e3-11e9-948b-bd5e1f39ac8e.png">
<img width="344" alt="Screen Shot 2019-08-03 at 11 41 50 AM" src="https://user-images.githubusercontent.com/15110789/62410251-b7f4fb00-b5e3-11e9-8b80-d5cfa442dce4.png">

Please let me know if I misunderstood or am missing something. 

Thank you for your time!

**Comment by johnli611** [comment]
I forgot to mention that the functions aren't showing up despite the index being successfully stored in Redux.

**Comment by johnli611** [comment]
The problem was that Redux serializes all state objects, which means functions won't be usable. 

Is there a plan in the future to separate out the index and the methods? E.g. so people can store the actual indexed data in redux and import/access the functions separately in whatever component they need?

**Comment by ts-thomas** [comment]
https://github.com/nextapps-de/flexsearch#exportimport-index
does this help you?

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
