### ISSUE TITLE
Token position should not affect match

### ISSUE THREAD

**Issue by tommiv** [nextapps-de/flexsearch#121]
I've encountered a strange bug and not sure if it's mine misuse of the library or a real bug in it:

I build an index in Russian language, using `natural` for tokenizer/stemmer. It seems to work, but:

```javascript
    const FlexSearch = require('flexsearch');
    const natural = require('natural');

    const tokenizer = new natural.AggressiveTokenizerRu();

    const index = new FlexSearch({
        tokenize: str => tokenizer.tokenize(str.toLowerCase()),
        encode:   str => natural.PorterStemmerRu.stem(str),
    });

    const data = [
        {id: 0, item: 'Молоко овсяное'},
        {id: 1, item: 'Молоко кокосовое'},
        {id: 2, item: 'Овсяное молоко'},
        {id: 3, item: 'Кокосовое молоко'},
    ];

    for (let it of data) {
        index.add(it.id, it.item);

        const debug = tokenizer
            .tokenize(it.item)
            .map(x => natural.PorterStemmerRu.stem(x));
        console.log(debug);
    }

    console.log(index.search('молоко').map(id => data[id]));
```

"Молоко" is a russian word for "milk". So this code emits this:

```
⇒  node src/index.js
[ 'молок', 'овсян' ]
[ 'молок', 'кокосов' ]
[ 'овсян', 'молок' ]
[ 'кокосов', 'молок' ]
[
  { id: 2, item: 'Овсяное молоко' },
  { id: 3, item: 'Кокосовое молоко' }
]
```

As you can see, tokenizer and stemmer does its job pretty well, tokens are ok, the only difference is their positions in array. However, the search function returns only two results in which the item line **does not start** from the search.

This is definetely not a case with English (or maybe with default index options):

```javascript
    const index = new FlexSearch();

    const data = [
        {id: 0, item: 'Milk oat'},
        {id: 1, item: 'Milk coconut'},
        {id: 2, item: 'Oat milk'},
        {id: 3, item: 'Coconut milk'},
    ];

    for (let it of data) {
        index.add(it.id, it.item);
    }

    console.log(index.search('milk').map(id => data[id]));
```

emits

```
[
  { id: 0, item: 'Milk oat' },
  { id: 1, item: 'Milk coconut' },
  { id: 2, item: 'Oat milk' },
  { id: 3, item: 'Coconut milk' }
]
```

and this is right.

After some debugging I still don't get a pattern here. Some examples:

```
        {id: 0, item: 'не Молоко овсяное'}, // NO
        {id: 1, item: 'Молоко кокосовое'}, // NO
        {id: 2, item: 'Овсяное молоко'}, // YES
        {id: 3, item: 'Кокосовое молоко'}, // YES
        {id: 3, item: 'молоко'}, // NO
        {id: 3, item: 'не молоко'}, // NO    
        {id: 3, item: 'не молоко молоко'}, // NO
        {id: 3, item: 'много разных слов and even English here молоко'}, // NO
```

UPDATE:

I serialized an index with `.export()` and here is what I've got:

```json
[
    [{
        "не": [0],
        "молоко": [1],
        "овсяное": [2],
        "кокосовое": [3]
    }, {
        "молоко": [0],
        "кокосов": [1],
        "молок": [2, 3]
    }, {
        "овсян": [0]
    }, {}, {}, {}, {}, {}, {}], {},
    ["@0", "@1", "@2", "@3"]
]
```

UPDATE 2:
With some further debugging I realized that encode step is performed BEFORE tokenization. Why so? Based on this ticket https://github.com/nextapps-de/flexsearch/issues/59, `encode` is designed for language extension, therefore it should be called on separate tokens, i.e. AFTER tokenizer. Otherwise it's impossible to stem each token, as it should be – there is no such entity as "token" on this step. At the same time, field `stemmer` of index constructor does not accept stemmer `function`.

**Comment by ts-thomas** [comment]
Language processing gets a big improvement: https://github.com/nextapps-de/flexsearch/blob/0.7.0/doc/0.7.0.md
Also the processing pipeline: https://github.com/nextapps-de/flexsearch/blob/0.7.0/doc/0.7.0.md#language-processing-pipeline
The pipeline has now "pre-encoding" and "post-encoding" phase, which solves that issue.

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
