### ISSUE TITLE
index.add fails for indexed subfield if it doesn't exist on an item

### ISSUE THREAD

**Issue by stefandesu** [nextapps-de/flexsearch#122]
I noticed that when you specify an index on a subfield (like `a:b`), it fails if any item in the data doesn't have that field. This should either just work (my opinion) or at least be documented [here](https://github.com/nextapps-de/flexsearch#complex-objects).

Example:
```javascript
const FlexSearch = require("flexsearch")

const index = new FlexSearch({
  doc: {
    id: "id",
    field: [
      "a",
      "b:a",
    ]
  },
})

const data = [
  { id: "1", a: "green", b: { a: "blue"} },
  { id: "2", a: "orange" },
]

index.add(data) // fails with "TypeError: Cannot read property 'a' of undefined"
```

Note that this didn't happen before. Back when I created issue #70, my example had this issue and still ran without an error, but now it doesn't

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
