### ISSUE TITLE
Remove() not working with id for documents

### ISSUE THREAD

**Issue by MatteoBassan** [nextapps-de/flexsearch#123]
Hello, I tried removing documents from the index by passing id, as mentioned in documentation as "the fastest method".
This way, i cannot remove the document.
Then, i tried removing the document by passing the document as remove argument, and this way it worked. (Attacched snippet)
Am I missing something? Is it supposed to work like this?

Edit: i think this issue is somewhat related to #100 

````
var FlexSearch = require("flexsearch");

var docs = [{
    data: {
        id: 0,
        title: "Foo",
        body: {
            content: "Foobaz"
        }
    }
}, {
    data: {
        id: 1,
        title: "Bar",
        body: {
            content: "Foobar"
        }
    }
}];

var index = new FlexSearch({
    debug: true,
    profile: 'default',
    doc: {
        id: "data:id",
        field: [
            "data:title",
            "data:body:content"
        ]
    }
});

index.add(docs);
index.remove(docs[1]) //<-- This one works, document is deleted
index.remove(1) //<-- This one NOT. Document is still searchable

console.log(index.search('bar'))
````

**Comment by cezarsmpio** [comment]
Mine is not working either.. Even `.add` is not updating the documents.

For example:

```js
const docs = [{ id: 1, text: 'a', id: 2, text: 'b' }];
index.add(docs);

index.search('b') -> finds `b`

delete docs[1];

index.add(docs);

index.search('b') -> `b` is still searchable
```

By doing what you suggested worked for me as well.

**Comment by lludol** [comment]
Same here!

Flexsearch is not production ready!

**Comment by lludol** [comment]
@MatteoBassan and @cezarsmpio 
I found a solution by looking at the source code:
```javascript
index.remove({ id: 1 });
```

**Comment by kgosselinCoe** [comment]
Has the same problem, can be dirty quickfixed
`index.remove(index.find(id));`

**Comment by Christilut** [comment]
My id field is on `_id` so had to use `index.remove({ _id: '123' })`. 

Would be good to update the docs with this.

**Comment by asimnazir** [comment]
The only workaround working for me is : index.remove(index.find(id))
Any idea when can it be fixed ?

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
