### ISSUE TITLE
[TS] Types are incomplete

### ISSUE THREAD

**Issue by PascalSenn** [nextapps-de/flexsearch#124]
Hello there.

Good to see that there are types now. 
There is a part missing though. 

The types only support `add(id: number, o: T);` but not `add(T:[])`
as in: https://github.com/nextapps-de/flexsearch#addupdateremove-documents-tofrom-the-index

**Comment by PascalSenn** [comment]
Actually there are several issues. 
I.E. SearchResult is also broken.

**Comment by PascalSenn** [comment]
Also there are several any return types

**Comment by gritschf** [comment]
@PascalSenn I fixed some errors in this PullRequest https://github.com/nextapps-de/flexsearch/pull/115/files

But the version `0.6.31` is not published yet :(

**Comment by zetsnotdead** [comment]
Any ETA on 0.6.31? :)

**Comment by ts-thomas** [comment]
https://github.com/nextapps-de/flexsearch/issues/126#issuecomment-553304470
