### ISSUE TITLE
Where is 0.6.30 and CHANGELOG?

### ISSUE THREAD

**Issue by peterbe** [nextapps-de/flexsearch#126]
I got an email from Dependabot about `Bumps flexsearch from 0.6.22 to 0.6.30.`
But where is 0.6.30? It's not in the [Releases](https://github.com/nextapps-de/flexsearch/releases):
<img width="1002" alt="Screen Shot 2019-09-11 at 10 41 02 AM" src="https://user-images.githubusercontent.com/26739/64707214-b2ab8b80-d480-11e9-9318-7bc619b2cc8b.png">
It's clearly [on npmjs](https://www.npmjs.com/package/flexsearch/v/0.6.30) 

Also there's no mention of any of this in [the CHANGELOG](https://github.com/nextapps-de/flexsearch/blob/master/CHANGELOG.md).

**Comment by peterbe** [comment]
And confusingly, it's [version 0.6.31](https://github.com/nextapps-de/flexsearch/blob/5006282de371f2a52d9c8269af5659c48339baa7/package.json#L3) in the `package.json` file.

**Comment by ts-thomas** [comment]
Sorry the package.json was updated but the code never gets published, because it was not stable. That is being fixed very soon in 0.7.0

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
