### ISSUE TITLE
flexsearch add async creates promises but does not return them

### ISSUE THREAD

**Issue by ed4becky** [nextapps-de/flexsearch#128]
I was hoping to use flexsearch's add function in async mode using promises.  I found that add creates a lot of promises, but doesn't return any.

on line 1273 the add function recursively calls itself, having done some parsing:

> fn.call(self, id, content, callback);

this recursive call results in a promise being created on line 920 and returned on line 936:

> const promise = new Promise(function(resolve){
> 
>                             setTimeout(function(){
> 
>                                 self.add(id, content, null, _skip_update, true);
>                                 self = null;
>                                 resolve();
>                             });
>                         });
> 
>                         if(callback){
> 
>                             promise.then(callback);
>                         }
>                         else{
> 
>                             return promise;
>                         }

However the function call on line 1273 does not capture the return value, so the promise is orphaned.  It eventually resolves, but no one has the reference to it.  Instead, the index itself is returned on line 1322, before the add processing is complete

Summary: what is returned in an async call to add is a premature reference to the index, not a promise.

If the function call on 1273 captured and returned the promise, there would still be a problem, because:
1) flexsearch creates a promise for each field if the field references an array
2) flexsearch creates a promise for each document if the add function has received an array of documents.

So if I have an array of 2 documents, and I want to index 2 fields, 4 promises get created.  If the returning of a promise were fixed, the code would return the first of the 4 promises, and when that first promise is resolved, the calling code would continue with a partially indexedFlexSearch object.

There are two ways this could be fixed

1) collect all the promises in an array, and return Promise.all(<promise array>) when all the fields/documents have been initiated. 
2) abstract out the processing of an array of documents/array of fields into a separate function, and encapsulate the entire call in one Promise.
3) some hybrid of 1 & 2

1: still means a LOT of promises are created if there are many documents and/or fields
2: could create a performance issue
3: don't know what this would look like

Here is my function:
createIndex(table: string, fields: string[], rows: any[]): Promise<FlexSearch> {

>     this.indices[table] = new FlexSearch({
>       encode: 'icase',
>       tokenize: 'full',
>       threshold: 0,
>       worker: false,
>       cache: false,
>       async: true,
>       doc: {
>         id: 'id',
>         field: fields
>       }
>     });
> 
>     return this.indices[table].add(rows);
>   }

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
