### ISSUE TITLE
It doesn't work for persian texts

### ISSUE THREAD

**Issue by hsiami** [nextapps-de/flexsearch#129]
I used below option for FlexSearch but It doesn't work!?

var index= FlexSearch.create({
    encode: "icase",
    tokenize: "reverse",
    rtl: true
});

index.add(1, "سلام دنیا")
index.length=> 1

persisted value => [[{},{},{},{},{},{},{},{},{}],{},["@1"]]

index.search("سلام") => []

**Comment by johnparn** [comment]
Good to know. I was just looking into FlexSearch as a potential candidate for a search service for persian among other languages. @hsiami , did you ever find a solution to this?

**Comment by ts-thomas** [comment]
Would be nice if you can help me to define a language settings for persian: https://github.com/nextapps-de/flexsearch/blob/0.7.0/doc/0.7.0.md

I just need some informations about the language:
1. An example of a text with a lot of special chars along with another example of the __same__ text where this special chars was removed (normalize charset)
2. The sign/character which separate words (e.g. a whitespace)
3. Has it right-to-left encoding?
With these information I can easily provide a definition for this language.

**Comment by ts-thomas** [comment]
Do not use any of the latin encoder will solve this.
