### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by PascalSenn** [nextapps-de/flexsearch#13]
Pretty neat. Performances really well. 

I read in #7 _"Flexsearch is a micro library whose complexity we want to keep as low as possible in the core. "_

What about sorting? We are currently considering replacing our list filters by flexsearch. It would be nice to use the same index also for sorting.

**Comment by ts-thomas** [comment]
I have already thought about sorting. This requires the indexing of more complex objects to sort by different attributes from the index. In this case, the flexible weighting of these attributes for a search would also be possible. I do not know exactly what your search requirements are, but when it comes to filtering, you can already do that pretty well with FlexSearch.

Define:
```js
var index = {};

function add(id, cat, content){
    return (index[cat] || (
        index[cat] = new FlexSearch()
    )).add(id, content);
}

function search(cat, query){
    return index[cat] ? index[cat].search(query) : [];
}
```
Add content to the index:
```js
add(1, "action", "Movie Title");
add(2, "adventure", "Movie Title");
add(3, "comedy", "Movie Title");
```
Perform queries:
```js
var results = search("action", "movie title"); // --> [1]
```

This way you can also provide different settings for each category.

**Comment by pantchox** [comment]
this is a good solution for categories, but what about sorting by time?

**Comment by ts-thomas** [comment]
Custom sorting is supported now: https://github.com/nextapps-de/flexsearch#custom-sort

**Comment by ThomasG77** [comment]
I don't find "Custom sort". It seems it has been dropped since 0.7? Wrong deduction on my side  or removed?
