### ISSUE TITLE
Faceted search support?

### ISSUE THREAD

**Issue by nithinkashyapn** [nextapps-de/flexsearch#131]
Hi, 

Awesome library and really great benchmarks.
Is there any way to achieve faceted search? I am trying to build an e-com search using this with Gatsby.

Thanks

**Comment by ts-thomas** [comment]
Hm yes and no. The `where ` clause might help to filter results by attributes, also `tags`. Both will merged together in 0.7.0. You can also add "virtual fields" to the index which is not included in document results, this way metadata could be indexed. All in all that topic gets an improvement very soon.

**Comment by nithinkashyapn** [comment]
Sounds cool, Looking forward to it.
