### ISSUE TITLE
Clarity in the README re: setting web worker

### ISSUE THREAD

**Issue by khaledallen** [nextapps-de/flexsearch#132]
I believe that the instructions in the README for using web-workers has an error. In the README, it says the following is the correct way to create workers:

```
var myIndex = new Flexsearch({
    tokenize: "forward",
    depth: 3,
    doc: {
        id: "id",
        field: [
            "title"
        ]
    },
    worker: 2
});
```

However, when I use this, my searches return no results. Changing it to plural works:
```
var myIndex = new Flexsearch({
    tokenize: "forward",
    depth: 3,
    doc: {
        id: "id",
        field: [
            "title"
        ]
    },
    workers: 2
});
```

Suggest confirming and updating the README. I encountered the discrepancy in the last 10 minutes of a hackathon, which was really exciting! I could not for the life of me find the problem, and we went with another solution, but I went back afterwards to see why it suddenly stopped working and this is what I discovered.

**Comment by khaledallen** [comment]
Actually, this may not be a typo. If there's something wrong with the search elsewhere, having a `worker` property defined might be breaking it, while `workers` bypasses it entirely. Ignore for now.

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
