### ISSUE TITLE
Proximity search support

### ISSUE THREAD

**Issue by ishanuda** [nextapps-de/flexsearch#133]
Hi,

Is the library support for proximity search?

Thank you very much.

**Comment by ts-thomas** [comment]
Yes, that is called "contextual index": https://github.com/nextapps-de/flexsearch#contextual-search
The parameter "depth" is the max distance from one to another word. But it needs set before indexing. Changing the depth within the query is actually not supported.

**Comment by ishanuda** [comment]
hi,

Thank you very much I will give it a try and come with the feedback.
