### ISSUE TITLE
Error with Documents (Field-Search)

### ISSUE THREAD

**Issue by ishanuda** [nextapps-de/flexsearch#134]
Hi,
I am trying to use the library with Node.js.
When I am trying to search with the following I am getting the below-mentioned error.

```
import * as FlexSearch from 'flexsearch';

private flexSearch: any;

constructor() {
  this.flexSearch = FlexSearch as any;
}
```

```
 const docs = [{
  id: 0,
  title: 'Test title one',
  cat: 'Test category one',
  content: 'Test content one',
 }, {
  id: 1,
  title: 'Test title two',
  cat: 'Test category two',
  content: 'Test content two',
}];
```

```
 const index = this.flexSearch.create({
  encode: 'icase',
  tokenize: 'full',
    doc: {
    id: 'id',
    field: [
     'title',
     'cat',
     'content',
   ]},
 });
```
` index.add(docs);`

```
 const res = await index.search([
  {
    field: [ 'title', 'cat', 'content' ],
    query: 'title',
    bool: 'and',
  }, {
   field: [ 'title', 'cat', 'content' ],
   query: 'category',
   bool: 'or',
  },
]);
```

 [Nest] 11660   - 10/13/2019, 2:53:20 PM   Cannot read property 'search' of undefined +9ms
[0] TypeError: Cannot read property 'search' of undefined
[0]     at w.search (node_modules\flexsearch\dist\flexsearch.node.js:27:287)
[0]     at SearchService.<anonymous> (dist\search\search.service.js:175:41)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (dist\search\search.service.js:13:58)

If I search with a single field it gives the result, but with multiple fields, it gives the above error.
Please help.

Also, I would like to know what is Field-Search (v0.7.0), Is this a release that I can download supporting field search?

kind regards.
shan

**Comment by ishanuda** [comment]
HI,

Any fixes for the following errors?

**Comment by jladbury** [comment]
I have a similar or identical problem. I set up the indexer in my own class like this:
```
class C9indexer {
	index;

	constructor(events: IEvent[]) {
		// console.time('index construction');
		let columnNames = c9.appVar.document.chronology.descriptor.columnDescriptors.map(o => o.name);
		let fieldDefinitions = {'id':'id'};
		fieldDefinitions['field'] = columnNames;

		this.index = new FlexSearch({
			'encode': 'icase',
			'tokenize': 'strict',
			'threshold': 1,
			'resolution': 3,
			'depth': 2,
			'doc': fieldDefinitions
		});
		this.index.add(events);
		// console.timeEnd('index construction');
	}
}
```
Then create a new instance of the class:
```
	c9.appVar.indexer = new C9indexer(c9.appVar.document.chronology.events);
```
These queries both work fine, returning the expected number of results:
```
a = c9.appVar.indexer.index.search("Ms F")
a = c9.appVar.indexer.index.search({query: "Ms F",bool: "or"})
```
But this one gives a similar error to the one reported in this bug:
```
a = c9.appVar.indexer.index.search([{query: "Ms F",bool: "or"},{query: "Routine",bool: "or"}])
Uncaught TypeError: Cannot read property 'search' of undefined
    at w.search (flexsearch.min.js:30)
    at <anonymous>:1:29
```
Could you confirm that it is the same bug, and if so give some idea of when it might be fixed?

**Comment by timo-jj** [comment]
Hi all :) 

I'm still having the same issue too.

`Error in render: "TypeError: Cannot read property 'search' of undefined"`

`
      const index = new FlexSearch({
        depth: 3,
        doc: {
          id: 'id',
          field: [
            'title',
            'client',
          ],
        },
      });

     index.add(this.list);

      const newList = index.search([
        {
          query: this.flexSearch,
          bool: 'and',
        },
        {
          query: this.clientName,
          bool: 'or',
        },
      ]);

      return newList;

`

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.

**Comment by fhollste** [comment]
I have this same issue with v. 0.7.31
Single field works but is not getting enriched with the code
```
index.search([
    {
      query: 'something',
      enrich: true,
      limit: 1000,
      field: 'record:title',
    },
  ])
```
