### ISSUE TITLE
Null and empty checking for search parameter

### ISSUE THREAD

**Issue by Pmurs** [nextapps-de/flexsearch#135]
I'm adding in a search function to a list of documents in a vue application and was getting an evaluation error on `index.search(searchString)`. Adding in a quick `if (!searchString) return unfilteredDocs;` solved the problem but it really seems like this is something that FlexSearch should handle gracefully. I would expect a null or undefined search string to simply not filter any results out of my set since the user won't have defined a search string yet when they first load the page.

Similarly, running a search with an empty string `""` returns no results when, intuitively to me, at least, it should be returning all the items in the index. This is posing an issue to me because I have a specific field filter next to my search bar and I'd like to be able to be able to use a 'where' block to chain the two search options together into a single call but the search string needs to be able to be empty even if the field filter is active.

This is how I've managed to solve the problem but there's no good reason for the solution to need to be this complex.
```
if ($comp.searchString && $comp.searchString.length) {
          return $comp.index.search($comp.searchString, {
            where: function(item) {
              return (
                !$comp.courseFilter || item.courses.includes($comp.courseFilter)
              );
            }
          });
        } else { // I shouldn't need to do this
          return $comp.index.where(item => {
            return (
              !$comp.courseFilter || item.courses.includes($comp.courseFilter)
            );
          });
        }
```

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
