### ISSUE TITLE
Position of the matched text in an Index

### ISSUE THREAD

**Issue by samsel** [nextapps-de/flexsearch#136]
Is there an option to retrieve the position of the searched text in a given string that flexsearch matches? would be super useful to generate a preview of the content.

Let us say there are two strings in the index
1: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. `
2. `It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.`

If I search using flexsearch for query `printing` it will return string 1.

now, with the returned index id, I also want to show a preview (+ or - 4 words from the matched text) - example: `text of the printing and typesetting industry.` Is there a way to do this?

**Comment by ts-thomas** [comment]
This is actually not supported. It could be provided by a future plugin. Also you can try to solve this manually. After getting back the result from indexed documents you need to find the first occurrence of the given query.

**Comment by ajl000** [comment]
It would be great if this could be supported

**Comment by TehShrike** [comment]
> This is actually not supported. It could be provided by a future plugin. Also you can try to solve this manually. After getting back the result from indexed documents you need to find the first occurrence of the given query.

Could you give me a tip as to what parts of the API to poke at to start writing a plugin that would return the location of matches?

**Comment by haikyuu** [comment]
First of all, thanks for this amazing library. That's some great engineering work.

> This is actually not supported. It could be provided by a future plugin. Also you can try to solve this manually. After getting back the result from indexed documents you need to find the first occurrence of the given query.

That defeats the point of the library. If I had to implement the exact algorithm used to perform search, I wouldn't use the library in the first place.

A good enough solution is to return just the index of the (first letter of the) occurrence in the string. 

> a future plugin

Is there an API for adding plugins? any examples?

**Comment by bobvanderlinden** [comment]
I was using fusejs, where the search results could be nicely highlighted with the matches it has found. However, the quality wasn't that great. I tried flexsearch, where the configurability is better to increase the quality of our search results, however it is impossible to highlight the results, so I'm going to look at other libraries right now.

Some indication on how to implement such a feature would help move someone forward with this library. Whether it is built on top of flexsearch or not is not really a problem for me. Any suggestions on where to start?

**Comment by ilmari-lauhakangas** [comment]
> Some indication on how to implement such a feature would help move someone forward with this library. Whether it is built on top of flexsearch or not is not really a problem for me. Any suggestions on where to start?

In https://help.libreoffice.org/latest/help.js see

`// Regex for highlighting the match`

and related stuff.

**Comment by BernhardBehrendt** [comment]
> I was using fusejs, where the search results could be nicely highlighted with the matches it has found. However, the quality wasn't that great. I tried flexsearch, where the configurability is better to increase the quality of our search results, however it is impossible to highlight the results, so I'm going to look at other libraries right now.
> 
@bobvanderlinden Do you maybe ha a hint who you've get further on this topic?

**Comment by bobvanderlinden** [comment]
I'm currently doing a regex lookup on the resulting documents for words in the query. First split the query by ` ` to get the words in the query. Create a regex that includes all of these words, by joining them using `|`. Then find all matches in the found document. Using those matches and their index and length I can highlight those findings. It doesn't support fuzzy searching.

One implementation can be found here:
https://github.com/verwijsafspraken/verwijsafspraken/blob/5fe4da30f8dbac922c8da44b4eff712a9d2e6971/src/search.js#L86
