### ISSUE TITLE
Unable to use a document for Chinese (CJK) searching

### ISSUE THREAD

**Issue by jason102** [nextapps-de/flexsearch#137]
So I have the following code using a document to store an object (Attendee):
[https://stackblitz.com/edit/react-ts-j8jysd](https://stackblitz.com/edit/react-ts-j8jysd)

But as you can see by the output, only 1 Attendee is printed to the screen (Attendee with id 9). There should be 6 printing out: Attendees with ids 0,3,7,1,2,5 as they all have text with the Chinese character 中 in them. 

So then I tried this code, not using a document:
[https://stackblitz.com/edit/react-ts-3r66hn](https://stackblitz.com/edit/react-ts-3r66hn)

This approach works - ids 0,3,7,1,2,5 are returned. Is this a bug with FlexSearch documents, or am I doing something wrong? Thanks!

**Comment by ts-thomas** [comment]
In your first link you search for `我` which is included in 6 and 9.
