### ISSUE TITLE
Advanced query example?

### ISSUE THREAD

**Issue by bengry** [nextapps-de/flexsearch#138]
I'm trying to use FlexSearch for building a search that acts a lot like the lucene language, so support for logical operators (using either `AND`, `NOT` or `+`, `-` respectively as well as `OR`), quotes/exact phrase match ("foo bar" won't match the text "bar foo").

From the README's supported features table it looks like FlexSearch can do that, but I couldn't seem to get it to work using even a "wasteful" configuration, as well as a basic query:
```js
const index: Index<string> = FlexSearch.create({
  tokenize: 'full',
  encode: 'extra',
  stemmer: false,
});

index.add(1, 'foo');
index.add(2, 'bar');
index.add(3, 'foo bar');
index.add(4, 'bar foo');

const values = index.search([
    { query: 'foo' },
    { query: 'bar' },
]); // values is an empty array
```

If I use the string overload of `search`: `index.search('foo bar')` it does find id 3 and 4, but how can I specify that only one of them is required for example, or that the I want the full query as a phrase (i.e. id 3 is valid, 4 is not).

So, a couple of questions:
1. Am I missing something?
2. Is what I want to do even possible with FlexSearch? If so, how can I achieve that? Ideally I'd just configure the operators in the `create()` call, and then `search()` can parse it automatically based on that.

**Comment by ts-thomas** [comment]
This expression is not supported actually:
```js
const values = index.search([
    { query: 'foo' },
    { query: 'bar' },
]); 
```
https://github.com/nextapps-de/flexsearch#field-search

**Comment by bengry** [comment]
@ts-thomas  So is there a way to achieve what I want above? I didn't fully understand from your response.

**Comment by kgosselinCoe** [comment]
you mean like :

> Limit the result:
>
>index.search("John", 10);

?
or search exactly the term "foo bar" 
https://github.com/nextapps-de/flexsearch#find--where

**Comment by bengry** [comment]
No, I'd just like a way to search by multiple terms with either an AND/OR between them.
The idea was to get something like [lucene](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html) working - where I feed FlexSearch with their a plain query string from the user, or parse it into an AST of sorts and then feed it to FlexSearch.

**Comment by kgosselinCoe** [comment]
something like 

```
let search = "foo bar";
let terms = search.split(' ');
let searchOptions = [];
for(let key in terms){
  searchOptions.push(
    { 
      field: "fieldName",
      query: terms[key],
      bool: "and"
    }
  )
}
let results = index.search(searchOptions);
```
You could use the bool logic

**Comment by ts-thomas** [comment]
Example from the documentation...

Search different queries on multiple fields:
```js
var results = index.search([{
    field: "title",
    query: "foo"
},{
    field: "body",
    query: "bar"
}]);
```

Search different queries on the same field (and control bool):
```js
index.search([{ 
    field: "title",
    query: "foo",
    bool: "or"
},{ 
    field: "title",
    query: "bar",
    bool: "or"
}]);
```
It did not tested it, but if not working this is something which gets support very soon.

**Comment by kgosselinCoe** [comment]
works in ^0.6.30

**Comment by bengry** [comment]
@ts-thomas is there a way to provide the NOT operator? Or support for precedence for operators?
examples:
1. NOT/- operator (in lucene): `foo -bar` will give back all results containing "foo" that do _not_ contain "bar".
2. Operator precedence: `(foo AND bar) OR baz` - will give back all results containing both "foo" and "bar", or results that contain "baz" (unrelated to if they contain, or not, "foo", "bar" or both).

**Comment by kgosselinCoe** [comment]
1. https://github.com/nextapps-de/flexsearch#logical-operators
2. Would be interisting

**Comment by licarijd** [comment]
It looks like searching different queries on the same field (and control bool) does not work for > 2 queries:

index.search([{ 
    field: "title",
    query: "foo",
    bool: "or"
},{ 
    field: "title",
    query: "bar",
    bool: "or"
},{ 
    field: "title",
    query: "test",
    bool: "or"
}]);

In this example, we only get results containing "foo" or "test"

**Comment by kgosselinCoe** [comment]
Is it the same for "and" and "not" ? Because I've only been using the "and" operator and it seems to work properly

**Comment by licarijd** [comment]
I can confirm that "and" works for > 2 queries. "or" does not work for > 2 queries.

**Comment by licarijd** [comment]
@kgosselinCoe I just opened a PR to solve this: https://github.com/nextapps-de/flexsearch/pull/141

**Comment by ts-thomas** [comment]
sadly that is actually not possible: `(foo AND bar) OR baz`
but it is something which is also on my wishlist. when the 0.7.0 is finally out, that is something I could take my focus on.

**Comment by ts-thomas** [comment]
Here is the old post about this topic: #42 
It might be a perfect time to change syntax when extending this feature.

**Comment by bengry** [comment]
@ts-thomas I didn't see that issue on my previous search. Too bad it's not supported.
I hope it's taken into account as a feature request in a future release. This is what we wanted to use Flexsearch (or others) for.

**Comment by timo-jj** [comment]
Hi all :) 

Search different queries on multiple fields are still not working.

```
index.search([{ 
    field: "title",
    query: "foo",
    bool: "or"
},{ 
    field: "title",
    query: "bar",
    bool: "or"
},{ 
    field: "title",
    query: "test",
    bool: "or"
}]);
```

Any help will be highly appreciated!
Thank you!

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
