### ISSUE TITLE
Is custom sorting on search not supported?

### ISSUE THREAD

**Issue by peterbe** [nextapps-de/flexsearch#139]
The [Custom sort](https://github.com/nextapps-de/flexsearch/#custom-sort) seems to only sort the results. 

I have 10,000 documents indexed and I search with a limit of 10 and those 10 are now sorted according to `popularity`. I'm doing:
```javascript
const indexResults = this.index.search({
  query: q,
  field: "title",
  limit: 10,
  sort: (a, b) => b.popularity - a.popularity,
  suggest: true
});
```

**But it still seems to sort on "matchness" (or "relevance") and NOT on my `popularity`.**

What I want, when I type `wa` that the document that contains a `wa` anywhere and has the highest `popularity` should appear first. If there are, 10,000 documents and 1,000 that technically match `wa` I want those 1,000 to be sorted by `popularity`. 

(PS. I tried using `sort: "popularity"` but that sorted the results the wrong direction and doing `sort: "-popularity"` didn't work)

**Comment by peterbe** [comment]
I'm trying to understand what it says [here](https://github.com/nextapps-de/flexsearch/issues/57#issuecomment-469155531) on the topic of "Field boosting" but that topic seems to be about searching on `title^10`, `summary^5`, `body^2`, `appendix^1` etc. 
In my case, I only have 1 field to search on.

**Comment by peterbe** [comment]
Here, I temporarily added a print (red) of each document's `popularity`. 

*Searching for `j`*
<img width="415" alt="Screen Shot 2019-11-14 at 1 24 47 PM" src="https://user-images.githubusercontent.com/26739/68884911-2d439200-06e2-11ea-8c0f-87e0795d5030.png">

*Searching for `javas`*
<img width="414" alt="Screen Shot 2019-11-14 at 1 25 38 PM" src="https://user-images.githubusercontent.com/26739/68884977-4ea47e00-06e2-11ea-963d-c7ea6d7941e9.png">

**Why didn't it find `JavaScript basics` since it has a popularity of `229.146`??**

**Comment by ts-thomas** [comment]
Yes, sorting by external attributes (like popularity) through the whole index isn't actually supported. It just sort by relevance through the whole index and perform custom sorts limited to the result. When the "boost" feature comes back, that could be solved.

**Comment by peterbe** [comment]
> When the "boost" feature comes back, that could be solved.

I thought boost was just a way to give preference to one field over another. Will this benefit me if there's only 1 field?

Also, is this going to come in 0.7? Or something after that?

**Comment by peterbe** [comment]
One thing that could work for me is that I index an array of strings in a specific order. 
I.e. I have this:
```javascript
[
  {title: "Miami Herald", popularity: 1.0},
  {title: "Washington Herald", popularity: 0.5},
  {title: "Orlando Herald", popularity: 1.5},
]
```
and I turn it into:
```javascript
["Orlando Herald", "Miami Herald", "Washington Herald"]
```
(highest popularity first)
Then would that be respected when I search for `hera`?

**Comment by peterbe** [comment]
Actually. I tried that. It works really well! Here's what I did:

```diff
-    Object.entries(titles).forEach(([uri, title]) => {
-      this.index.add(uri, title);
-    });
+    Object.entries(titles)
+      .sort((a, b) => b[1].popularity - a[1].popularity)
+      .forEach(([uri, info]) => {
+        this.index.add(uri, info.title);
+      });
```

Doing a couple of searches this way seems to produce pretty good results. At least good enough that I'm no longer blocked and can continue to use FlexSearch.

**Comment by ts-thomas** [comment]
Yeah nice idea. It works when the results have the same relevance. If not the relevance gets prioritize over the sort. But you can control relevance. Relevance isn't a float value, it is an integer. You can control the "resolution" of how many different relevance values exist ("slots"). This way you can force to sort by an external value regardless of the relevance:

```js
new FlexSearch({
    threshold: 0,
    resolution: 1
});
```

This will categorize each text to the same relevance "slot".
