### ISSUE TITLE
VOTE: How to chain deeply nested boolean via the query payload?

### ISSUE THREAD

**Issue by ts-thomas** [nextapps-de/flexsearch#144]
Actually the best solution I came up is:

```js
index.search({
    "and": [{
        "or": [{
            field: "title",
            query: "foo"
        },{
            field: "title",
            query: "bar"
        }]
    },{
        "not": [{
            field: "content",
            query: "foo"
        },{
            field: "content",
            query: "bar"
        }]
    }]
});
```

Accordingly to this example the results should:

- contain the term "foo" OR "bar" in the field "title"
- does NOT contain the term "foo" or "bar" in the field "content"

Since "or" is the default logic if nothing was specified, the example above could be simplified to:

```js
index.search({
    "and": [{
        field: "title",
        query: ["foo", "bar"]
    },{
        field: "content",
        query: ["foo", "bar"],
        bool: "not" // applies to the query array!
    }]
});
```

Also the current style is supported by passing a field "bool" which always applies to its own scope of passed queries.

Do you see any improvements or suggestions?

Anyone knows a good workaround of reducing the complexity by resolving the optimal order of boolean chains?

**Comment by brooke-stephens-cbc** [comment]
Yeah this structure would be very useful.  For things like filtering out certain queries and having flexible query chains.

**Comment by baptistemanson** [comment]
It is non ambiguous and a nice iteration over Elasticsearch.
Probably respecting the order of declaration would help defining the behaviour of the short circuit-ed AND.
