### ISSUE TITLE
Support for special characters?

### ISSUE THREAD

**Issue by jason102** [nextapps-de/flexsearch#145]
It seems adding documents with fields containing special characters like !%#^$^(*) etc is not supported by FlexSearch? When I do the following test and export the index it seems all special characters are filtered out (and thus not searchable)?
[https://stackblitz.com/edit/js-ncg2p3](https://stackblitz.com/edit/js-ncg2p3)

But for some reason I feel like maybe I'm doing something wrong as it seems nobody has mentioned this issue yet?

**Comment by ts-thomas** [comment]
Please try to use a different "encoder", the default encoder will remove special chars by splitting through this regex `/W+/`, you need to provide a custom encoder (takes a string, returns an array of words/terms).
