### ISSUE TITLE
Window is not defined in 0.7.0 Node

### ISSUE THREAD

**Issue by baptistemanson** [nextapps-de/flexsearch#149]
Hi all,

On 0.7.0:
```zsh
yarn add https://github.com/nextapps-de/flexsearch.git\#0.7.0
node --version
# returns v12.13.1 
```
With this minimal code sample:
```js
const flex = require("flexsearch");
```
I get this error:
```bash
ReferenceError: window is not defined
 at /x/node_modules/flexsearch/dist/flexsearch.node.js:34:794
    at Object.<anonymous> (/x/node_modules/flexsearch/dist/flexsearch.node.js:34:913)
    at Object.<anonymous> (/x/node_modules/flexsearch/dist/flexsearch.node.js:34:919)
```
It does work in 0.6.32

**Comment by mtr** [comment]
This affects me too.

**Comment by talaikis** [comment]
+1

**Comment by vladnicula** [comment]
+1

**Comment by devboldly** [comment]
+1

**Comment by crapthings** [comment]
still doesn't work?

**Comment by crapthings** [comment]
remove package-lock.json and remove flex in package.json

then reinstall works

**Comment by deldrid1** [comment]
I use yarn and am experiencing the same thing on ```"flexsearch": "nextapps-de/flexsearch#0.7.0"```.  ```0.6.22``` does not have this problem (but I have other issues there so I was trying the latest and greatest).

I removed `yarn.lock`, removed `node_modules` and did a fresh `yarn install` and am still seeing this issue :(

Any ideas?

**Comment by ts-thomas** [comment]
Please use the latest version which should solve that issue.
