### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by georgyfarniev** [nextapps-de/flexsearch#150]
Hello @ts-thomas. What is the project status? I see it idle now. I remember you had big plans for it, and we even planned to use it for our product (JFYI).

**Comment by kiviaj** [comment]
Flexsearch is awesomely efficient and fast, thumbs up @ts-thomas, how are you?

**Comment by MarcCoet** [comment]
I am also interested to know! Flexsearch is so good. I'd really like to see where it goes.
If it is a matter of ressources, maybe you could activate a way for people and companies to support this project @ts-thomas ?!

**Comment by dperetti** [comment]
It doesn't look good 😕

**Comment by mbykov** [comment]
alas, alas
