### ISSUE TITLE
[Documentation] React working example

### ISSUE THREAD

**Issue by melkir** [nextapps-de/flexsearch#153]
I can't get flexbox to work in a React environment. Simply by using `require`, I have following error:
> Cannot read property 'define' of undefined

Here's my minimal example: https://codesandbox.io/s/react-typescript-zgbo5

I would like to know if either I'm doing something wrong or either it's related to an issue with the library 🥺

**Comment by melkir** [comment]
This seem's to be related to https://github.com/nextapps-de/flexsearch/issues/72

**Comment by ts-thomas** [comment]
Please try to use the latest version. Does this issue still occurs?

**Comment by melkir** [comment]
The issue is no longer present on the latest version, thank you 👍
