### ISSUE TITLE
Is it possible to not save the document data?

### ISSUE THREAD

**Issue by stevenroussey-privicy** [nextapps-de/flexsearch#155]
Would like to have an index only, with identifiers so we can find the record via sqlite. Is this possible?

**Comment by clibu** [comment]
There is no option for this. That said FlexSearch does not use the documents it stores, other than for index Import & Export. 

It is easy enough to add an option to stop FlexSearch storing the documents.  I did that, but have now switched to using [MiniSearch](https://github.com/lucaong/minisearch).

**Comment by ts-thomas** [comment]
Yes it is, just pass `store: false` in your options when creating the index.
