### ISSUE TITLE
0.7.0 webpack oddity...

### ISSUE THREAD

**Issue by dimaqq** [nextapps-de/flexsearch#156]
<img width="630" alt="Screenshot 2020-02-10 at 17 56 10" src="https://user-images.githubusercontent.com/662249/74134868-a2b1f680-4c2e-11ea-8417-b712276b0ca6.png">

version info:
```
+flexsearch@nextapps-de/flexsearch#0.7.0:
+  version "0.7.0"
+  resolved "https://codeload.github.com/nextapps-de/flexsearch/tar.gz/128395ffbe96fcb636d40b0828ca4521e2cf7669"
```

I've added flex search to the reducer for now, the idea is that once all "users" are loaded from the server, client will build an index.

```
+import FlexSearch from "flexsearch";

...

+      {
+        // Maybe own action...
+        const index = new FlexSearch({encode: "advanced", tokenize: "strict"});
+        Object.entires(draft.users).map(([k, v]) => index.add(k, v));
+      }
```

Here, `draft` is an `immer` draft, and I expect `v` to be an object of shape `{username: "xxx", email: "eee", ...}`.

I'll dig into this more tomorrow ofc, just wanted to give an early hail-shot :)

**Comment by mahnunchik** [comment]
The same error.

```
// flexsearch@nextapps-de/flexsearch#0.7.0
import FlexSearch from 'flexsearch';
new FlexSearch();
//flexsearch__WEBPACK_IMPORTED_MODULE_1___default.a is not a constructor
```

Empty object is imported from `flexsearch` module.

**Comment by mahnunchik** [comment]
`import FlexSearch from 'flexsearch/dist/module/flexsearch';`

This import works as expected.

**Comment by dimaqq** [comment]
Interesting suggestion, @mahnunchik ! Direct substitution results in a failed build however:

```
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/flexsearch/dist/module/flexsearch.js:1:11053

Read more here: https://bit.ly/CRA-build-minify
```

But I guess that's my problem, I'll post an update here if/when I figure this out :)

**Comment by dimaqq** [comment]
According to `es-check`, node_modules/flexsearch/dist/module/flexsearch.js is an ES6 module.
Meanwhile I still have react-scripts in my project and build, and looking through old issues (https://github.com/facebook/create-react-app/issues/3734) it seems that react-scripts / uglify could not (cannot?) handle es6 modules in dependencies, but rather expect them to be precompiled to es5.

Thus I did:

```diff
-import FlexSearch from "flexsearch";
+import FlexSearch from "flexsearch/dist/flexsearch.es5.js";
```

And the build is happy. 🎉 
I bet there must be a better way by now, but this works and gets me out of a jam. 😅

**Comment by dimaqq** [comment]
I called it done too soon. `flexsearch_dist_flexsearch_es5_js__WEBPACK_IMPORTED_MODULE_5___default.a is not a constructor` ☹️

**Comment by dimaqq** [comment]
I can manually fix up `module/flexsearch.js` so that it builds in prod mode:
* beautify it back
* rename one minified variable `v` to a unique name

The original source code in question is here: https://github.com/nextapps-de/flexsearch/blob/128395ffbe96fcb636d40b0828ca4521e2cf7669/src/flexsearch.js#L2174-L2179

It's quite hard to make sense of it, the minified code has `for (let v, A; ...; ...) ...` and there's also `v` in the outer scope. Renaming this "inner" `v` solves the build error.

Perhaps it's a case of `temporal dead zone`? I can certainly see a hypothetical path through the code where `v` is used before it's set. Original source code uses unique variable names, so there's no problem there.

**Comment by ts-thomas** [comment]
Please use the latest version which solves that issue.

**Comment by mmm8955405** [comment]
o. 7.21 there is no flexsearch file
