### ISSUE TITLE
Search doesn't return result

### ISSUE THREAD

**Issue by shazgames** [nextapps-de/flexsearch#163]
The following code
```
var index = new FlexSearch("memory", {
	    encode: "balance",
	    tokenize: "forward",
	    threshold: 0
	})

const allData = await GetAllVideos() // load data from mongo db

	allData.map( item => {
			item.categories.forEach( it => {
				if(it === 'Babe') console.log(it)

				index.add(item._id, it)
			})
		})

	index.search('Babe', res => {
		console.log('Result', res)
	})
```
Returns
```
Babe
Babe
Babe
Babe
Babe
Babe
Babe
Babe
Babe
Babe
Babe
Result []
```

**Comment by nevf** [comment]
@shazgames Have you tried looking in the debugger to see what is happening. Has an index been created in ```add()```. If you step through ```search()``` you can also see where it iterates the index. 

Should be pretty straightforward to track the issue down. That said you code looks ok, however I'm not using the config options you are.

**Comment by Leyart** [comment]
See if https://github.com/nextapps-de/flexsearch/issues/96 could be similar to what you are experiencing

**Comment by shazgames** [comment]
Use this code: 
```
data.forEach(item => {
		item.categories.forEach(categoryName => {

			index.add(item.id, categoryName)
			console.log('Index: ', JSON.stringify(index, null, '\t'), '\n')
				
			console.log('Search result:', index.search('Babe').length, item.id)
			}
		})
	})
```

Result is: 
```
Index:  {
	"id": 0,
	"m": [],
	"c": "forward",
	"split": {},
	"v": false,
	"async": false,
	"threshold": 0,
	"b": 9,
	"depth": 0,
	"a": false,
	"h": [
		{
			"b": [
				"5e875772b1fb080c2eb182bb"
			],
			"ba": [
				"5e875772b1fb080c2eb182bb"
			],
			"bab": [
				"5e875772b1fb080c2eb182bb"
			],
			"babe": [
				"5e875772b1fb080c2eb182bb"
			]
		},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{}
	],
	"g": {},
	"f": {
		"@5e875772b1fb080c2eb182bb": 1
	},
	"u": false,
	"cache": false,
	"j": false
}
Search result: 1 5e875772b1fb080c2eb182bb
Index.h:  {
	"id": 0,
	"m": [],
	"c": "forward",
	"split": {},
	"v": false,
	"async": false,
	"threshold": 0,
	"b": 9,
	"depth": 0,
	"a": false,
	"h": [
		{
			"r": [
				"5e875772b1fb080c2eb182bb"
			],
			"re": [
				"5e875772b1fb080c2eb182bb"
			],
			"rea": [
				"5e875772b1fb080c2eb182bb"
			],
			"real": [
				"5e875772b1fb080c2eb182bb"
			],
			"reali": [
				"5e875772b1fb080c2eb182bb"
			],
			"realit": [
				"5e875772b1fb080c2eb182bb"
			],
			"reality": [
				"5e875772b1fb080c2eb182bb"
			]
		},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{}
	],
	"g": {},
	"f": {
		"@5e875772b1fb080c2eb182bb": 1
	},
	"u": false,
	"cache": false,
	"j": false
}
Search result: 0 5e875772b1fb080c2eb182bb

```

**Comment by shazgames** [comment]
I used JS Search and past code worked. It's seems like bug of this library

**Comment by nevf** [comment]
@shazgames Is it simply that you need to include ``` encode: "icase"``` ie. The index contains "babe" but you search is for "Babe".

I don't think this is a bug in flexsearch.

@Leyart He is only searching for a single term, so I don't see how #96 is relevant.

**Comment by shazgames** [comment]
@nevf anyway it doesn't work. I added {encode: "icase"} in FlexSearch but it's still returning 0. Is it normal that when i add new item in index, the Index.h always has 1 element like here https://github.com/nextapps-de/flexsearch/issues/163#issuecomment-614732188 ?

**Comment by nevf** [comment]
@shazgames I'm not seeing Index.h in the version of Flexsearch I'm using which is v0.6.30 Are you using the 0.7.0 branch? I assume this is the array of index keys.

If you step through ```search()``` where ```for(let z = 0; z < (resolution - threshold); z++){..``` is you should be able to see what is going wrong.

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
