### ISSUE TITLE
How to configure a field that has array of strings while creating index?

### ISSUE THREAD

**Issue by TheCodersPlayground** [nextapps-de/flexsearch#164]

**Comment by smnmmnn** [comment]
Feature is currently under Release Group C which is unreleased according to the docs

> Release Group C (unreleased)
 new core consists of a "Document Model" and an "Index Model" (that is the biggest improvement)
 implementation of "tags" rewritten
 "where"-clause was removed (fully replaced by tags)
 **support of nested arrays in documents**

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x which has support for this, thanks a lot.
