### ISSUE TITLE
No results when searching index for emoji

### ISSUE THREAD

**Issue by smnmmnn** [nextapps-de/flexsearch#166]
_index.search_ on an input like '😀' yields no results, even if the string has an exact match in the doc. Does this relate to encoding or tokenizing issues?

**Comment by ts-thomas** [comment]
Yes, it is related to the used "encoder", please try to use another encoder function (takes a string, returns an array of words/terms).

**Comment by kolaente** [comment]
Tried setting a different encoder, but couldn't get that to work: https://github.com/nextapps-de/flexsearch/issues/428
