### ISSUE TITLE
Relevance Scoring Comparison performance page is broken

### ISSUE THREAD

**Issue by nevf** [nextapps-de/flexsearch#167]
The page at https://raw.githack.com/nextapps-de/flexsearch/master/test/matching.html which is linked to in several places on https://github.com/nextapps-de/flexsearch is failing with:

````
GET https://cdn.jsdelivr.net/gh/weixsong/elasticlunr.js@master/example/elasticlunr.min.js net::ERR_ABORTED 404
DevTools failed to parse SourceMap: https://cdn.jsdelivr.net/npm/js-search@1.3.7/dist/umd/dist/umd/js-search.min.js.map
matching.html:288 bulksearch: 726.43896484375ms
matching.html:306 flexsearch: 693.559814453125ms
matching.html:310 Uncaught ReferenceError: elasticlunr is not defined
    at matching.html:310
````

**Comment by lukevp** [comment]
Looks like the elasticlunr package doesn't expose a minified version in the repo anymore and will need to be pinned to a release version.  This can be updated and in fact is already updated in the benchmark.html file in the repo.

https://cdn.jsdelivr.net/gh/weixsong/elasticlunr.js@0.9.6/example/elasticlunr.min.js

and then the page works.

I've submitted PR #181 to fix this.

**Comment by clibu** [comment]
@lukevp Thanks for that. Unfortunately I've given up on flexsearch as I came up against some issues that affect my usage and because development and developer support appear to have stalled. 

Instead I'm using [Minisearch](https://github.com/lucaong/minisearch) which is well supported, works very well, uses less memory (I think) and has result scoring.

**Comment by lukevp** [comment]
Thanks for the recommendation!  Minisearch looks like a good fit for my use case too.  I wasn't able to use something like elasticlunr or lunr.js because I want to implement a custom filter function on the results.

**Comment by clibu** [comment]
@lukevp Good to hear. The more people that use and support Minisearch the better. Then hopefully it will stay alive. I've got a minor issues with stemming I'm yet to raise in Minisearch.

**Comment by lukevp** [comment]
I ended up going back to flexsearch because there is not support for purging files from the index by ID, only by entire record, in mini search, and I am not able to manage the lifecycle of my objects at that level.

**Comment by clibu** [comment]
@lukevp Yes this was a bit of a problem for me as well. I was able to refactor the code to get the record before updating it, to get this to work with MiniSearch.  Wasn't a big deal for me, but I can see that might not be the case for others and it is an unusual requirement.

If you aren't dealing with a large volume of records another option is simply to delete and recreate the index.

There is a recently closed issue along the same lines.  https://github.com/lucaong/minisearch/issues/45

**Comment by ts-thomas** [comment]
https://nextapps-de.github.io/flexsearch/bench/match.html
