### ISSUE TITLE
Typescript return types missing in 0.6.32

### ISSUE THREAD

**Issue by sceee** [nextapps-de/flexsearch#172]
When using v0.6.32 in Typescript, the typescript compiler complains about several missing return-type annotations in the type definitions with error messages similar to `'registerLanguage', which lacks return-type annotation, implicitly has an 'any' return type.ts(7010)`:

![image](https://user-images.githubusercontent.com/11340487/79638142-5cc06400-8184-11ea-8f83-c7442f8db60a.png)
![image](https://user-images.githubusercontent.com/11340487/79638146-61851800-8184-11ea-98d0-8bf8d659aebc.png)

**Comment by haysclark** [comment]
@sceee I believe this issue should be closed.

Resolved by #173 
Diff: https://github.com/nextapps-de/flexsearch/commit/5dfb3de415745e7c40e77bf36cc9c80d0707e013
