### ISSUE TITLE
[Bug Report] Custom options are not used after calling clear method to reset index

### ISSUE THREAD

**Issue by mandalornl** [nextapps-de/flexsearch#176]
### Environment
**FlexSearch:** 0.6.32

### Steps to reproduce
1. Create `new FlexSearch` instance with some options e.g. `doc` settings.
2. Call `clear` on instance.
3. Add `data` to instance.

### Expected Behavior
Reinitialize with options passed during instance creation.

### Actual Behavior
Custom options are not preserved and defaults are used instead.

### Reproduction Link
https://jsfiddle.net/7yxsbLmw/

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
