### ISSUE TITLE
Search per named field (Github issue search style)

### ISSUE THREAD

**Issue by jwillp** [nextapps-de/flexsearch#177]
Hi,
I was wondering if it was possible to make searches using named fields in a similar fashion to the GIthub Issue Search:

Given:
```javascript
doc: {
    id: "id",
    field: [
      "title",
      "content",
      "assignee"
    ]
}
```
With an indexed document like:
```
{
    id: "1",
    title: "An Issue"
    content: "Content of an Issue",
    assignee: "John"
}
```
To be able to do a query like so:
```
title:"An Issue" assignee:"John"
```

Is there a way out of the box something like this?

Thank you!

**Comment by wbelk** [comment]
I think for this you would use multiple query and bool: 'and'

**Comment by jonrkarr** [comment]
This would be great to have. 

For comparison, Lunr supports this query syntax: https://lunrjs.com/guides/searching.html

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x which has support for this, thanks a lot.

**Comment by jonrkarr** [comment]
This sounds great! This will enable us to switch to flexsearch. Is there documentation about the supported search syntax?
