### ISSUE TITLE
Pagination with OR query

### ISSUE THREAD

**Issue by divyamakkar26** [nextapps-de/flexsearch#178]
I want to use page: true with bool: 'or', when I use each of them individually it gives me proper results but when I use them together in field search it gives me blank array

My code -
const searchIndex = new FlexSearch({
  doc: {
    id: 'searchId',
    field: ['searchContent'],
  },
});
searchIndex.search([{
      suggest: true,
      limit: 10,
      page: true,
      query: 'program',
      field: 'searchContent',
      bool: 'or',

    }, {
      suggest: true,
      limit: 10,
      page: true,
      query: 'assets',
      field: 'searchContent',
      bool: 'or',

    }], (results) => {
      res.send({ status: 200, results });
    });

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
