### ISSUE TITLE
Using pagination with multi-field search doesn't return result

### ISSUE THREAD

**Issue by RabbidDog** [nextapps-de/flexsearch#186]
#### What I am doing
I have multiple fields that the user can filter on. So the query text for each field would be different. And the result should be paginated because the table component can't handle large row sets.

What I would like to find out is how to use the format below along with pagination
`index.search([{
    field: "title",
    query: "foo"
},{
    field: "body",
    query: "bar"
}]);`
Ever better, if multiple query texts can be applied to the same field with "or"
Current attempts don't return any result. my search looks as follows
`index.search([{
    field: "title",
    query: "foo"
},{
    field: "body",
    query: "bar"
}], {limit: 100, page: true});`

#### expected behavior
pagination on multi-field search should return result

#### current behavior
getting empty result array

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
