### ISSUE TITLE
Adding additional components to search-terms

### ISSUE THREAD

**Issue by emresaracoglu** [nextapps-de/flexsearch#191]
Hi,

Is it possible to give examples of search terms for `key:value`?
for example, add links to the searched texts?

```
var data = [
     "term 1": "https://example.com/term1...",
     "term 2":"https://example2.com/term2"
];
```

Thank you

**Comment by ts-thomas** [comment]
You can use `Document` which can hold multiple indexes. Then you can apply query to specific fields. Also you can add various data to the index and the store, e.g. add a "term1" into the index and adding "https://example.com/term1" to the store, which is getting back in the results when using option `enrich`.
