### ISSUE TITLE
the search ignores the symbols

### ISSUE THREAD

**Issue by javierperini** [nextapps-de/flexsearch#197]
Hello,

I added flexsearch library to my application. This works very well in the most cases. However, I have problems when I try to perform searches that combine words and symbols like &, !, #, %. For example:

We have a collection with 4 items: 
   1. Course&Some
   2. Course#Another
   3. Course%Foo
   4. Course!Bar

When I try searching the term 'Course&' (ignore single quotes), the library returns 4 results, ignoring the symbol &. I expect one result (the item number one).
When I try searching the term 'Course&Another' (ignore single quotes), the library returns 3 results (items two, three and four). I expect zero results.

So, my questions are:

1. How should I proceed so that the library does not ignore the symbols when searching?
2. Is there a way to improve the behavior of the library with cases like the ones mentioned? 

I am using this configuration:

```
var index = new FlexSearch({
        encode: "advanced",
        tokenize: "full",
        depth: 3,
        threshold: 0,
        async: false,
        worker: false,
        cache: false,
        doc: {
            id: "Id",
            field: [
                "Field1",
                "Field2"
            ];
        }
    });
index.add(collectionItems);
```

I perform the search in the following way:

```
var params = { field: ["Field1", "Field2"], query: text, bool: "or" }

index.search(params, function (results) {
	//More code    
}

```
Thanks in advance.

**Comment by carlinmack** [comment]
I reckon the tokenize function full takes in your input and sanitises it, I would [define a custom encoding function](https://github.com/nextapps-de/flexsearch#flexsearch.tokenizer)

**Comment by jladbury** [comment]
I have the same problem, but not the expertise to write  a custom tokenizer (which is what the above link takes you to, rather than a custom encoding function). Help!

**Comment by carlinmack** [comment]
you can [choose a simpler tokenise function](https://github.com/nextapps-de/flexsearch#encoders) instead :)

**Comment by jladbury** [comment]
@carlinmack Thanks for taking an interest! I delved a little deeper and found that this works fine for my purposes:
```
tokenize: function(str){
	return str.split(/\s+/g);
}
```
I think it will also suit the riginal poster @javierperini.

**Comment by ts-thomas** [comment]
That issue basically is coming from the "encoder", not the "tokenizer". You need to assign that tokenize from example above in the field "encoder", e.g.:

```
encode: function(str){
	return str.split(/\s+/g);
},
tokenize: "forward"
```
