### ISSUE TITLE
Sorry but i need help with this

### ISSUE THREAD

**Issue by EloFran** [nextapps-de/flexsearch#198]
Hi all and thx,

Could someone tell me that I should modify so that it does not take into account the accents in the searches?

ex: Artículo . If i write "artículo", its good, but if write "articulo", no looking for.

I've been reading the documentation and following the add steps, but what I get is just that. Let's see if someone would be so kind as to tell me how to do it.

Greetings
Thx,

**Comment by kgosselinCoe** [comment]
I think you might find your answer in the encoder: https://github.com/nextapps-de/flexsearch#encoder-matching-comparison

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
