### ISSUE TITLE
Announcement: New release is coming during Dez 2020

### ISSUE THREAD

**Issue by ts-thomas** [nextapps-de/flexsearch#199]
Dear developers,

Thanks a lot you for your patience! I have a great announcement, there will be a new release during Dezember 2020 packed full with fixes and improvements. One of the most important change is the new structure of the code, which was implemented from the ground up to make future contribution a lot easier and even more straight forward.

Best Regards,
Thomas

**Comment by marcoancona** [comment]
Hi @ts-thomas, looking forward to the new release. Are there a lot of breaking changes expected from the current version or 7.beta? I just want to understand if it makes sense to start integrating the current version in our project or wait.

**Comment by ts-thomas** [comment]
Thanks @marcoancona, the application method interfaces will work much like the same as current version. I expect no many changes in current implementations.

**Comment by MarkTanashchuk** [comment]
Hello @ts-thomas, is it planned to make index.add()/index.init()/etc... asynchronous?

Now I faced problem that index.add(json) blocks main thread and whole DOM freezes for a few seconds

It would be nice if it became asynchronous in next update =)

**Comment by sali0** [comment]
Will there be an update to flexsearch-server?

**Comment by baptistemanson** [comment]
@MarkTanashchuk we decided not to use document based flexsearch but the simple index interface which is miles faster in indexing speed. As we were only doing simple OR and AND between the fields, it was trivial to reimplement those operations.

**Comment by MarkTanashchuk** [comment]
> @MarkTanashchuk we decided not to use document based flexsearch but the simple index interface which is miles faster in indexing speed. As we were only doing simple OR and AND between the fields, it was trivial to reimplement those operations.

I don't understand a bit how FlexSearch without document model might look like, can you provide an example?

**Comment by npearson72** [comment]
Any news on this?

**Comment by kr05** [comment]
I'm currently trying to make the new version work in node. Using the same implementation as the previous version leads to a "window is not defined" error. After looking through the code a bit, I noticed the node.js portion is commented out:
![image](https://user-images.githubusercontent.com/11833744/104071673-7ac06f80-51be-11eb-8bab-8744ba8b9d44.png)

I'm wondering what factory might be...

**Comment by SirUli** [comment]
@ts-thomas I guess the December 2020 was a bit too packed. Do you have an update on the timeline? Thanks in advance!

**Comment by airhorns** [comment]
👋 @ts-thomas is this project still something you're interested in maintaining? If not, would you consider giving permissions over to some folks you trust in the community to carry it forward in your absence? It'd be really great to get this release out and some of the pending PRs merged!

**Comment by Wallacy** [comment]
Without trying to be creepy, i just hope that @ts-thomas is well. Zero activities on github after Nov 1, 2020;

This project is awesome btw.

**Comment by boardend** [comment]
For everyone who is following this issue: see https://github.com/nextapps-de/flexsearch/issues/216
