### ISSUE TITLE
The benchmarks with different presets seem unfair

### ISSUE THREAD

**Issue by markogresak** [nextapps-de/flexsearch#20]
The benchmarks for query and memory tests use different presets, but compare to same config of other libraries. 
It would be helpful to be able to compare the difference of flexsearch performance between presets, while showing a full, unbiased picture.

**Comment by ts-thomas** [comment]
Basically, I see it that way too. Of course, to demonstrate that FlexSearch is very flexible, I have to go back to the different presets. The test would be fairer if the other libraries offer similar options of adjustment. But unfortunately they do not do that. If you have suggestions for better settings that meet the minimum requirements, then I would be very happy about it.

**Comment by jazz2222** [comment]
Not comments all doing well done

**Comment by ray1981jacob** [comment]
How do I retrieve my money from you

**Comment by ts-thomas** [comment]
I removed the table "memory comparison".
