### ISSUE TITLE
Problem finding parts of string

### ISSUE THREAD

**Issue by SetupCoding** [nextapps-de/flexsearch#200]
Using `"flexsearch": "^0.6.32"`

Given:

```
  const searchIndex = new FlexSearch({
        encode: 'extra',
        tokenize: 'full',
        threshold: 1,
        resolution: 9
  });
  searchIndex.add(1, '11ABRILE02WSDC0C');
```

I am getting:

```
        searchIndex.search('a'); // NO ENTRIES FOUND
        searchIndex.search('ab'); // NO ENTRIES FOUND
        searchIndex.search('abril'); // NO ENTRIES FOUND
        searchIndex.search('b'); // entry found
        searchIndex.search('1a'); // entry found
        searchIndex.search('br'); // entry found
```

I would like to know what I am doing wrong in the first 3 cases, since I am assuming that it should find `ab` if it can find `br`.

Many thanks in advance!

**Comment by SetupCoding** [comment]
I ended up switching to [Fuse.js](https://github.com/krisk/fuse). Even though it does have quite "inclusive" search results, it does find all the substring entries i this case.

**Comment by ts-thomas** [comment]
You just used an inappropriate encoder, the "extra" encoder is a text-only-optimized encoder and is excluding numbers.
