### ISSUE TITLE
Only works on single fields

### ISSUE THREAD

**Issue by npearson72** [nextapps-de/flexsearch#206]
If I have the following index:

```
const index = new FlexSearch({
  profile: 'score',
  doc: {
    id: 'id',
    field: ['title', 'description']
  }
});
```

With the following data:

```
    const doc = [
      {
        id: 1,
        title: 'foo',
        description: 'Hello world'
      },
      {
        id: 2,
        title: 'bar',
        description: 'How are you'
      }
    ];

```

As I type "foo" I get the first result. But as I continue to type "food world" the result is empty.

Why doesn't it match both the title and the description?

**Comment by ts-thomas** [comment]
You need to use the option `tokenize: "forward"` which is also known as "prefix search".
