### ISSUE TITLE
Chinese and English at the same time?

### ISSUE THREAD

**Issue by tesla-cat** [nextapps-de/flexsearch#207]
how to search mixed Chinese and English text?

**Comment by ts-thomas** [comment]
You need to define your own "charset" or "encoder" to make this possible. The readme contains some basics about language processing and how to customize it.

**Comment by mmm8955405** [comment]
> 您需要定义自己的“字符集”或“编码器”来实现这一点。自述文件包含一些关于语言处理以及如何自定义它的基础知识。

Are there any examples?

> You need to define your own "charset" or "encoder" to make this possible. The readme contains some basics about language processing and how to customize it.

Are there any examples?

**Comment by kjs104901** [comment]
This is working for me.

```javascript
function(str){
  let result = []
  result.push.apply(result, str.replace(/[\x00-\x7F]/g, "").split(""));
  str.split(/[^a-zA-Z0-9\u00C0-\u00ff]/g).forEach(t => {
    if (t.length > 0) {
      result.push.apply(result, t.toLowerCase().split(/[\p{Z}\p{S}\p{P}\p{C}]+/u));
    }
  });
  return result;
}
```
