### ISSUE TITLE
Performance compared to Elasticsearch

### ISSUE THREAD

**Issue by joshuaquek** [nextapps-de/flexsearch#208]
How does this compare to if one were to use an actual elasticsearch instance? (Just curious, and hopefully my question is a valid one too)

**Comment by ts-thomas** [comment]
You cannot really compare these because Elasticsearch is a framework which contains a search engine based on Apache "Lucene". Also Elasticsearch completely runs asynchronous. A direct comparison is not fair, FlexSearch will run probably 1 million times faster.
