### ISSUE TITLE
Need suggest search return only matching document value

### ISSUE THREAD

**Issue by jeromelarman** [nextapps-de/flexsearch#210]
Hello, 

It is possible to return only the field value matching to the suggestion ( not the entire document ) ?

In my current implementation, suggest feature seems to works as expected but return all the document body.

I don't know by advance wich field match in the document, so I can't build my autocomplete suggestion menu because I don't know which properties value of the document i could keep.

Thanks.

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, it supports custom stores, thanks a lot.
