### ISSUE TITLE
[Question] Conditional attributes search

### ISSUE THREAD

**Issue by carlos-mora** [nextapps-de/flexsearch#211]
I have a Positions table that "has many" People related. In the pivot table there are additional data like fromDate, toDate, etc. The backend alo provides a position.current attribute that point to the related Person in that position currently, or null if any.

That info is shown in a table in the frontend and I use FlexSearch to filter.

```
            this.flexSearch = new FlexSearch({
                encode: 'advanced', 
                tokenize: 'full',
                suggest: true,
                bool: 'or',
                doc: {
                    id: 'id',
                    field: [
                        'code',
                        'description',
                        'current:person:name'
                    ],
                },
            });

```

When current is null, obviously, I get an error: TypeError: can't access property "person", g is null

How do I overcome this? There is a way to say that 'current:person:name' must be tested when current is not null?

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
