### ISSUE TITLE
How best to return unindexed data for each match (as well as the ID)?

### ISSUE THREAD

**Issue by samdutton** [nextapps-de/flexsearch#22]
For each item that matches a query, I'd like to be able to get unindexed arbitrary data — not just its ID.

For example: for matches when searching Shakespeare plays, I'd like to be able to return the text of an individual line (which is indexed) but also play name, location, speaker, etc.

What's the best way to achieve this?

I can do this in Elasticlunr (for example) like this:

```
const index = elasticlunr(function() {
    this.addField('text'); // doc property to be indexed
    this.setRef('id'); // doc property that is the ID of each item
    for (const doc of docs) {
      // doc includes additional arbitrary data for each item: play, speaker, location, etc.
      this.addDoc(doc); 
    }
}
```

Would I simply need to create an object that maps IDs with item data, or is there a better way to do this?

Great project by the way — thanks so much for building this.

**Comment by ts-thomas** [comment]
Thanks for the praise. Indexing complex objects is one of the most top todos on my list. I'm sure that this feature comes shortly. In the meanwhile you can use a workaround for this purpose.

Assuming you have an array of objects:
```js
var data = [{
    id: 294578,
    title: "Movie Title",
    year: "2019",
    genre: "Adventure"
},{
    id: 193754,
    title: "Movie Title",
    year: "2019",
    genre: "Adventure"
}];
```

and you intend to search these data by movie title, the workaround looks like:
```js
var index = new FlexSearch();

data.forEach(function(movie, i){
    index.add(i, movie.title);
});
```
also split index by genres is conceivable #13 

When searching map the results with the initial data:
```js
var results = index.search("title").map(function(id){
    return data[id];
});
```

**Comment by samdutton** [comment]
Thanks for the quick response!

I'll keep an eye out for the complex-objects implementation.

Your workaround is pretty much what I came up with :) though I used an object with values (objects) keyed by ID — rather than an array.

I'll check out splitting indexes as well.

👍

**Comment by samdutton** [comment]
Wow! That was quick :). Thanks for the heads-up — I'll try it out.
