### ISSUE TITLE
stemmer custom function does not work

### ISSUE THREAD

**Issue by bertrand-riviere** [nextapps-de/flexsearch#221]
hello,
first thanks a lot for this nice lib!
i've tried to use a custom stemmer function and it does not work (the function is never called).
the same is true for both methods described in the doc:
- FlexSearch.registerLanguage('lang', { stemmer: customFunc, ...})
- new FlexSearch({ stemmer: customFunc , ...})
first i thought i was doing something wrong because i've found a unit test that is supposed to assert that this work ("Should have been stemmed properly (custom function)": https://github.com/nextapps-de/flexsearch/blob/6e3ca4fa56dd81af6ba856972ac06d4e561ad136/test/test.js#L1181)
so i've cloned the repo and ran the tests myself.. i found out that if i comment out the stemmer option in this test, it still passes, which means the test does not assert anything (and i can clearly see that the custom function never gets called)

other users seem to encounter same king of problems: https://github.com/nextapps-de/flexsearch/issues/185
what do you think of the workaround @kulikalov proposes (using a custom encoder instead)?: 
https://github.com/nextapps-de/flexsearch/issues/185#issuecomment-654174005

maybe you don't want to bother fixing this since you might focus on v0.7 but maybe you should update the doc in this case so that others do not waste time trying to use this.

just my two cents; since stemming is critical and that it is too bad to re-invent the wheel, maybe you should point to good stemming libs in the doc and do not implement it yourself

**Comment by ts-thomas** [comment]
The language processing has slightly changed in 0.7.x, you can pass custom stemmer but you also need to use one of the built-in encoder (which contains the pipeline which is processing the stemmer) or define your own custom charset.
