### ISSUE TITLE
Indexing number fields crashing the application

### ISSUE THREAD

**Issue by ishanuda** [nextapps-de/flexsearch#224]
Hi,

So happy to use the new version with new features.

However, got the following error when trying to index the number fields.
Do not know if this is the default behavior.
Correct me if I am wrong please and close the issue.

Thank you very much.

![flexsearch-error](https://user-images.githubusercontent.com/8893919/121864311-660e7780-cd1a-11eb-9e6a-32f039afeb93.jpg)

 [Here is the link to code sandbox:] (https://codesandbox.io/s/indexing-number-fields-flexsearch-9e790)

**Comment by ts-thomas** [comment]
Thanks for the report. This bug is now fixed in 0.7.1
