### ISSUE TITLE
Requesting a public chat room

### ISSUE THREAD

**Issue by ishanuda** [nextapps-de/flexsearch#225]
Hi,
I do not know if there is a public chat room related to this amazing library.

Would like to know about an existing public chat room for the community to talk freely (contributors, and users)
Ex: https://gitter.im, https://slack.com, or any other that can use.

If not exists, can you provide one that can be used for the community?

Thank you very much

**Comment by ts-thomas** [comment]
Hello, thanks a lot. That is a good suggestion. What do you think about the github discussion feature: https://github.com/nextapps-de/flexsearch/discussions ?

**Comment by ishanuda** [comment]
Hi,
Thank you for the reply.

This would be an open question for the community (developers, users) of the library.
If they are ok with the suggestion I have no problem.

Thank you very much.

**Comment by ts-thomas** [comment]
"The main intention is to separate the issues from the general discussions." absolutely yes. That what the section "discussions" is supposed to. I will prefer using same domain over creating an additional section of another domain.
