### ISSUE TITLE
Help: Indexing a huge JSON file with performance

### ISSUE THREAD

**Issue by ishanuda** [nextapps-de/flexsearch#227]
Hi,
I have a big file with JSON objects array returned by the Apache Solr server that needs to search using **flexsearch** library.

The JSON object is similar to the following.
```
{
        "id": "2b43dc16-36a5-4fa8-a92d-bbcaffb89975",
	"path": "some\\path\\to\\file\\name.pdf",
	"_version_": 1681536136523022336,
	"created": 20190917,
	"page_num": 2,
	"section": "28-14 - Some system",
	"content": "some content",
	"block": "some block"
},
```
The file size would be about 1GB or more than that.
My intention is to `consume the file and index using the node server with flexsearch` and send the result to the angular front end.

I read the file and added the objects to the index and got the result using the **Document**.
However, the process takes some time and it freezes the server until the process is over.

What is the best way to get the result in an efficient way including the performance concern? 

Suggestions would be really helpful.

Thank you very much.

**Comment by ts-thomas** [comment]
Create an index (this example has good memory-saving setting):

```js
const index = new Document({
    charset: "latin:extra",
    document: {
        id: "id",
        tag: "section",
        index: "content",
        store: true
    }
});
```

Remove the tag "section" when you did not need it in your queries.

Add data by using `async` and `await` gives you a non-blocking memory-friendly workaround:

```js
for(let i = 0; i < data.length; i++){
    await index.addAsync(data[i]);
}
```

When you reach the default memory limit of a node process just use some flags to increase memory when starting the task, e.g.:

```js
node --max-old-space-size=8192 index.js
```

**Comment by ishanuda** [comment]
Hi,
Thank you for the reply.

I have several files to read and index and provided the result.
The file selection depends on the user's request with the search query.

I also have the intention to break these large files into small files and store them in a relevant folder in order to read faster.

Ex. If I have a file with large content called ```index.json``` breaking it into ```index-1.json, index-2.json, index-3.json, etc.```

However, after the index has been created and data added to the index, 
would it be ok to store the configured index (as a cache) per file when the first request comes,
and search from the cached index when the second time the user needs to search for a particular file?

If that is ok, I won't be needing to re-open the file from the FS, read and re-configure the index from the begining.

I am afraid of the memory problem in the above case.

**NOTE: there is a requirement to search by opening multiple files as well.**
**Note: there would be thousands of uses requesting for the search and need to provide the result faster.**

Thank you very much.

**Comment by ts-thomas** [comment]
That sounds more complicated, I think we need more details of your scenario. If you like you can create a simple example with jsfiddle or something else and move this "issue" to a discussion: https://github.com/nextapps-de/flexsearch/discussions

**Comment by taieb-tk** [comment]
We are facing the same issue, it starts to get slower and slower, and then the add. stops. We are using about 25 gb.
Any ideas on a solution?
