### ISSUE TITLE
Getting a preview for search results

### ISSUE THREAD

**Issue by Fiday** [nextapps-de/flexsearch#229]
### Discussed in https://github.com/nextapps-de/flexsearch/discussions/228

<div type='discussions-op-text'>

<sup>Originally posted by **Fiday** June 17, 2021</sup>
Hi, 
I'm trying to create a preview for the search results on my gitlab pages site built with Hugo. I'm pretty new to flexsearch and don't even know where the created Index file is saved/can be found (so testing is kinda hard)
Does anybody have some advice/examples of how it can be done? 

Thanks in advance
Fiday</div>

**Comment by ts-thomas** [comment]
Discussed in #228
