### ISSUE TITLE
null pointer exception if field value to index is undefined or null

### ISSUE THREAD

**Issue by develar** [nextapps-de/flexsearch#231]
Here https://github.com/nextapps-de/flexsearch/blob/08c5baf832738d5fa218b2edccb504789f4497ad/src/document.js#L249 we don't check that value is null or undefined, but `is_array` method expects not-null value.

I suggest to use [Array.isArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray) instead of own util method. This standard method is [widely supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#browser_compatibility).

Thanks a lot for the amazing lib! I stumbled upon the fact that every other lib produces incorrect (prefix search) and not expected (too many results) results, but `flexsearch` result set is what logically expected.

**Comment by ts-thomas** [comment]
Thanks for the report, it is fixed in v0.7.11
