### ISSUE TITLE
@0.6.32 & v0.7.x: index incorrectly sorts first item added

### ISSUE THREAD

**Issue by haysclark** [nextapps-de/flexsearch#233]
>Note: I see the same issue in FlexSearch 0.7.x... all items but the first are sorted in order of keyword occurrences.

I ran into this issue when adding the `filter` option to create(). Basically, the first item added to the index does not get sorted correctly. Adding it as the 2nd item will result in the expected sorting. ...assuming you know what the users is searching for. 😄 
I put together an interactive demo of the issue on [CodeSandbox](https://codesandbox.io/s/flexsearch0632-no-spacing-sort-behavior-wlbze?file=/src/index.ts).

```typescript
import FlexSearch from "flexsearch"

type IndexableDocument = Record<string, unknown>

const index = FlexSearch.create<IndexableDocument>({
  filter: value => value.length > 1,
})
const documents: IndexableDocument[] = [
  { id: `one`, body: `bird cat dog` },
  { id: `two`, body: `cat dog cat` },
  { id: `none`, body: `bird fish dog` },
  { id: `five`, body: `cat fish cat fish cat other cat other cat` },
  { id: `four`, body: `cat bird cat other cat other cat` },
  { id: `three`, body: `cat other cat other cat` },
]
documents.forEach(({ id, ...indexFields }) => {
  const serializedDoc = JSON.stringify(indexFields)
  index.add(id as number, serializedDoc)
})

const results = index.search("cat")
console.log(results) 

// outputs: [ 'five', 'four', 'three', 'one', 'two' ] 
// expected: [ 'five', 'four', 'three', 'two', 'one' ]
```

**Comment by haysclark** [comment]
Hmmm... I think will close these because the example I put together was too contrived. Using a 'filter' does not add sorting, it was just a coincident that items were sorted in the order I was hoping for.

**Comment by haysclark** [comment]
This issue is in FlexSearch 0.7.x... I'll let author confirm if sorting should work.

**Comment by ts-thomas** [comment]
related to #234
