### ISSUE TITLE
Question - is it possible to order index by word occurrences (hits)

### ISSUE THREAD

**Issue by haysclark** [nextapps-de/flexsearch#236]
I'm trying to do a simple blog search that sorts search results by keyword occurrences. The default FlexSearch behavior seems to try to retain the original order of the content as it was added to the Index... which makes sense for a book. Is this possible with flexsearch@0.6.x or flexsearch@0.7.x?

Here is a simple example, where each page just a 'id' and the 'body'. When I search for a keyword, 'cat', I want the posts with the most occurrences of 'cat' first.

```typescript
import FlexSearch from "flexsearch"
type IndexableDocument = Record<string, unknown>

const index = FlexSearch.create<IndexableDocument>({})

const document = [
  { id: `threecat`, body: `cat meows. cat stretch. cat sleep.` },
  { id: `onecat`, body: `cat is still asleep` },
  { id: `catcatdogdog`, body: `dog barks at cat. cat runs from dog.` },
  { id: `onedog`, body: `dog sleeps` },
  { id: `threedog`, body: `dog woofs. dog chases tail. dog sleeps` },
]
document.forEach(({ id, body }) => {
  index.add(id as number, body)
})

index.search("cat") // goal: [ 'threecat', 'catcatdogdog', 'onecat' ]
index.search("dog") // goal: [ 'threedog', 'catcatdogdog', 'onedog' ]

// actual flexsearch@0.6.x output, respects order of original content
// cat: ["threecat","onecat","catcatdogdog"]
// dog: ["catcatdogdog","onedog","threedog"]
```

**Comment by ts-thomas** [comment]
Unfortunately this isn't supported by FlexSearch. The scoring algorithm does not take occurrences into account, because it will compete against the query strategy from FlexSearch. In most cases, the occurrence of a term has almost no relevance to the search query, as long the term isn't included multiple times in the query as well.

I can recommend you to use 0.7.x over 0.6.x, the new version improves everything, especially the order in results, use of contextual indexes and suggestions.

**Comment by haysclark** [comment]
@ts-thomas With FlexSeach 0.7.x can I author a custom Pipeline to respect occurrences?

**Comment by ts-thomas** [comment]
Good news, it is now supported by the option "boost": https://github.com/nextapps-de/flexsearch#index-options

Example:

```js
const index = new Index({ 
    boost: function(word, term, index){
        let factor = 0;
        for(let i = 0; i < word.length; i++){ 
            if(word[i] === term) factor++; 
        }
        return factor || 1;
    }
});
```

**Comment by mmm8955405** [comment]
let factor = 0;
        for(let i = 0; i < words.length; i++){ 
            if(words[i] === term) factor++; 
        }
        return factor || 1;


As a result, the first words appear in the top ranking. Not the most

**Comment by mmm8955405** [comment]
term ，Appear other words！！！！..........
