### ISSUE TITLE
0.7.11: Can't add array of documents to Document index

### ISSUE THREAD

**Issue by stefandesu** [nextapps-de/flexsearch#237]
The documentation says: ["Just pass the document array (or a single object) to the index"](https://github.com/nextapps-de/flexsearch/blob/master/README.md#addupdateremove-documents-tofrom-the-index). However, that doesn't seem to work for me:

```js
const { Document } = require("flexsearch")

const document = new Document({
  index: ["content"]
})

const docs = [
  {
    id: 1,
    content: "Hello world"
  },
  {
    id: 2,
    content: "What's up?"
  }
]

// this does not work (no results)
// document.add(docs)

// this does work (one result)
docs.forEach(doc => document.add(doc))

console.log(document.search("hello"))
```

**Comment by ts-thomas** [comment]
Sorry, the documentation was not updated on this line. You can't add an array of items anymore, you need to add them one by one.
