### ISSUE TITLE
Typescript support is missing

### ISSUE THREAD

**Issue by ali-habibzadeh** [nextapps-de/flexsearch#24]
Are there any plans to support typescript?

**Comment by ali-habibzadeh** [comment]
you are ts-thomas. surely ts already won :)

**Comment by ts-thomas** [comment]
I've created a git project to this topic: https://github.com/nextapps-de/flexsearch/projects/3
The TypeScript port will include the plain core functionality without any tooling (async, cache, worker, etc.) to make this to a perfect base for other language migrations and ports.

**Comment by ScreamZ** [comment]
Any ambients types available ?

**Comment by ts-thomas** [comment]
#94

**Comment by jkwilliams375** [comment]
Is there a clear cut list of steps anywhere on how to get flexsearch to work properly in a Typescript project? Do you just need to add this[ updated file ](https://github.com/nextapps-de/flexsearch/commit/479c500f7e0dba44843f619831d349b6c03bbd74) to the TS project and it will handle the type conversions?
