### ISSUE TITLE
Can not index number fields

### ISSUE THREAD

**Issue by ishanuda** [nextapps-de/flexsearch#246]
Hi,
After updating the library to v0.7.2 again the number fields indexing gives the error.

Example: https://codesandbox.io/s/indexing-number-fields-flexsearch-9e790?file=/src/index.js
Thank you

**Comment by ts-thomas** [comment]
Hello, thanks for the report. I just forget to commit one line of code. This is now fixed and included in the build v0.7.21

**Comment by ishanuda** [comment]
Thank you very much
