### ISSUE TITLE
bool search gives errors

### ISSUE THREAD

**Issue by ishanuda** [nextapps-de/flexsearch#247]
Hi,

I have configured the search index and trying to search the index using bool conditions (AND/OR).
However, the search gives me an error saying **' Cannot read property 'search' of undefined'**

Example: https://codesandbox.io/s/flexsearch-bool-search-pdz3h?file=/src/index.js

Thank you very much.

**Comment by ts-thomas** [comment]
Thanks for the example. The query configuration from your example is not supported. This for example will work:

```js
var result = index.search([{
  field: "title",
  query: "some query"
},{
  field: "title",
  query: "some other query"
}]);
```

The boolean flag needs to be set in the root of the configuration payload and can just switch between "or" / "and" boolean model for all fields in this query. What I can suggest is split your query into two or more multiple queries or apply your boolean logic on top of the result-set. Theoretically when using a combination of 4 boolean flags, it could have a lot of different combinations (dependent on how the bool needs to be applied like inner/outer). I came up with an idea which is already on my list for upcoming features, where you can call helper methods to combine any complex and/or/xor pattern easily.

**Comment by ishanuda** [comment]
Hi,
Thank you for the answer.

01. Can I use an array for the field?
ex: 

```
var result = index.search([{
  field: ["title", "subTitle", "content"]
  query: "some query"
},{
  field: ["title", "subTitle", "content"]
  query: "some other query"
}]);
```
02. I did not understand where to configure the boolean flag in the root and use switching the flag.

03. If you can please modify the example or direct me with an example existing with this kind of case that would be really helpful.

Thank you very much.
