### ISSUE TITLE
Is it possible to negate/disallow a term?

### ISSUE THREAD

**Issue by RShohoney** [nextapps-de/flexsearch#252]
This is not a bug, but just a question.  If the answer is no, then I think this is a feature request. Let me know if this is not the right place for this question.

I've looked through the docs a few times, but I can't seem to find a definitive answer.  Is it possible to negate/disallow a term?  Say I want to find all of the records that _don't_ contain a term. In similar full text search systems, we can use `+` to require a term be present and `-` to require a term must not exist.  Is something like this possible?  If not, is there a relatively similar work around?  If not, how difficult would this be to implement?

**Comment by RShohoney** [comment]
It appears that this was discussed in https://github.com/nextapps-de/flexsearch/issues/42 but it appears that the "not" operator was either dropped, or is not documented.

**Comment by ts-thomas** [comment]
Such a filter needs to be applied manually when getting back the enriched result.
