### ISSUE TITLE
Multiple search terms across multiple fields

### ISSUE THREAD

**Issue by Fannon** [nextapps-de/flexsearch#257]
Hi,

first let me thank you for this library. I'm using it for a browser extension (https://github.com/Fannon/search-tabs-bookmarks-and-history) along with Fuse.js and I really prefer the speed of flexsearch over it. It's quite noticable!

I do have a question regarding expected behavior and how to achive a search behavior.

Given that I'm using a document index with two or more fields. 

```json5
// example document
{
  field1: 'ABC',
  field2: 'XYZ',
}
```

So if I search for 'ABC XYZ' I'd like to get a search match, but it looks like I don't. The reason seems to be that there is no single field which contains both ABC and XYZ? 
Chosing the bool: 'and' operation is also not working, because it seems to require that the same search term appears in ALL of the fields. The default 'or' mode seems to be interpreted that at least one of the fields must contain all of the search terms.

What I really want to do is to search across all of the fields in the index and treat all of the fields of a document index as one unit for matching the search terms within.

So, I could work around this by following your advice to implement the boolean logic in my own code:

> Instead of applying your bool logic to a nested object, you can apply your logic by yourself on top of the result-set dynamically. This opens hugely capabilities on how you process the results. Therefore, the results from the fields aren't squashed into one result anymore. That keeps some important information, like the name of the field as well as the relevance of each field results which didn't get mixed anymore.

To do that, I stopped using the Document index altogether and instead created multiple normal indexes per field. That did work, but leaves some effort of correctly implementing the correct conditions to me. I wonder if this is not some feature that would be nice to have handled on library level when using document indexes? Of course that depends on how common or uncommon my use-case / expectation is.

Sorry, I didn't find enough time to add some conrete code examples. If it helps, I could come up somthing.

Best regards,
Simon

**Comment by robokozo** [comment]
I have a similar issue. For example

Given
```
[{ id: 1, text: "foo" }, { id: 2, text: "bar" }, { id: 3, text: "foo bar" }, { id: 4, text: "bar foo" }]
```

and my search query is `foo bar`  I will get back items 3 and 4. I think it would be great if I can configure my search to "or" between the terms of the query so that 1 and 2 would also be included.

My current solution is to split my query by spaces, run multiple searches, and combine my results afterwards. 

I agree that having the ability to have the library 'or' between terms in a query would be a great quality of life improvement.

**Comment by ts-thomas** [comment]
You can use the suggest feature: https://github.com/nextapps-de/flexsearch/issues/327
or you can use some kind of custom "union" to the result: https://github.com/nextapps-de/flexsearch/issues/314
