### ISSUE TITLE
Are there any papers on Contextual-based Scoring?

### ISSUE THREAD

**Issue by julesbravo** [nextapps-de/flexsearch#26]
I’d love to read more on this scoring strategy.

**Comment by ts-thomas** [comment]
Related to this issue #23 there is actually no public paper available, but I plan to make a public version available shortly. The concept in the readme (https://github.com/nextapps-de/flexsearch#contextual-search) is a good base to explain how contextual scoring works. There is a green gradient which demonstrates the relevance of context (from the perspective of a initial word as root, e.g. "Word 4"). Contextual scoring only comes into play when the query has more than 1 term and increase effect for each additional term (that note is actually missing in the readme).
