### ISSUE TITLE
[Question] Index whole String but store part of it?

### ISSUE THREAD

**Issue by bphenriques** [nextapps-de/flexsearch#261]
Hello! 👋 

Given a document:
```json
{
   "id": 32424324,
   "title": "title",
   "content": "quite large content"
} 
```

Is it possible to index both fields and prune.`content` to, for example, 90 characters (as I only need to provide a small preview of the content) to optimize the store? As of now I can get by having an additional field `preview` which is a truncated version of `content` :)

Thank you for the amazing project 🙇

**Comment by ts-thomas** [comment]
What you can do ist create an index an do not use builtin store. Instead after adding the object to the index prunse the specific data field and push data objects manually to your own store object by using the ID as key.
