### ISSUE TITLE
Request: add types definition(.d.ts) to npm package

### ISSUE THREAD

**Issue by blackhuman** [nextapps-de/flexsearch#263]
There is a index.d.ts file in the project root of flexsearch codebase, but it was not included in the npm published package, nor in the package.json types field. Could it be included in npm package at the next release?
I also found that the index.d.ts seems outdated, which was not match the real js code.
Thanks very much for your all efforts to build this lib.

**Comment by Losses** [comment]
#266 would help

**Comment by Losses** [comment]
Use this: https://www.npmjs.com/package/@types/flexsearch
