### ISSUE TITLE
Flatten results

### ISSUE THREAD

**Issue by robokozo** [nextapps-de/flexsearch#272]
I'm use flexsearch to do some web client side filtering of some objects. While I appreciate getting the search results broken down by the object field that matches, it is often unnecessary in my use cases and I find myself having to flatten and filter my results down to a unique set. I feel like performance can be improved when searching in this proposed mode because flexsearch can ignore already matched items.

Thanks!

**Comment by ts-thomas** [comment]
You also use just one document index. After getting back the result you can merge the fields like the example above.
