### ISSUE TITLE
export keys are not correct

### ISSUE THREAD

**Issue by tiejunhu** [nextapps-de/flexsearch#273]
in current recur implementation of export, the result key is somehow got all connected with dot. so instead of "reg, cfg, map, ctx", now the exported keys are "reg, reg.cfg, reg.cfg.map, reg.cfg.map.ctx"

**Comment by g-harel** [comment]
Yes, this took me hours to figure out. Would be very helpful to flag it in the docs with a workaround. Here's what I used:

```
 const fixedKey = key.split(".").slice(-1)[0];
 ```

**Comment by ts-thomas** [comment]
This is now fixed in v0.7.23
Further improvements to provide Promise.all() compatible export ist coming in next version.
