### ISSUE TITLE
Why doesn't stemming work in Node?

### ISSUE THREAD

**Issue by peterbe** [nextapps-de/flexsearch#280]
This could be a user-error. If so, I'm sorry, but it's not easy to understand how to use it. 
I know the language, in my use case is, English (`en`) so I want it to find "repositories" and I search for "repository" and vice versa. I tried this:

```js
const { Index, Document, Worker } = require("flexsearch");

const index = new Index({language: 'en', tokenize: "forward", stemmer: true})
const docs = ["Procurement is a word", "But also procurements is a word", "Repository is a word"]
docs.forEach((doc, i) => {
  index.add(i, doc)
})

const results = index.search('repositories', {limit: 10})
for (const key of results) {
  console.log(key, docs[key])
}
```
It's not finding anything. And if I search for `procurement` I want it to match `Procurement` *and* `procurements`.

Demo here: https://glitch.com/edit/#!/insidious-roan-note

**Comment by ts-thomas** [comment]
I will update the docs shortly to show how to use extern stemmer library.
