### ISSUE TITLE
Switch to "and" boolean logic when doing field specific search

### ISSUE THREAD

**Issue by jackz314** [nextapps-de/flexsearch#282]
According to the documentation, you are able to "switch the default "or" logic from the field search into "and"" like this:

```javascript
index.search(query, { 
    index: ["title", "content"],
    bool: "and" 
});
```

But how can you achieve the same thing when doing a field-specific search? Supplying `bool: "and"` to each object didn't seem to work. e.g. with different queries for different fields:
```javascript
index.search([{
    field: "record:title",
    query: "some query",
    limit: 100,
    suggest: true
},{
    field: "record:title",
    query: "some other query",
    limit: 100,
    suggest: true
}]);
```

**Comment by ts-thomas** [comment]
You will need to apply such a logic manually when getting back the result. There is a plan to provide logical helpers which could be applied to the result for this purpose.
