### ISSUE TITLE
export only exports one field

### ISSUE THREAD

**Issue by jackz314** [nextapps-de/flexsearch#288]
I'm trying to export a Document index that has multiple fields, but it seems like only one field is exported. Does anyone know what might be the cause of this? Or is this a bug?

```javascript
await docIndex.export((key, data) => {
    console.log("Index key:", key);
    ...
  });
```
Output ("title" is one of the indexed fields):

> Index key: reg
> Index key: title.cfg
> Index key: title.map
> Index key: title.ctx

I'm using the latest version (0.7.2), I also tried the master branch, neither worked.

**Comment by ts-thomas** [comment]
This is now fixed in v0.7.23
Further improvements to provide Promise.all() compatible export ist coming in next version.
