### ISSUE TITLE
Code failing for Chrome Browser version 63

### ISSUE THREAD

**Issue by uditvishnoi2** [nextapps-de/flexsearch#296]
Hi , we have updated to latest version of library v0.7.22 , after that code is throwing error on Chrome 63.0.3239.132

`Uncaught SyntaxError: Invalid regular expression: /[\p{Z}\p{S}\p{P}\p{C}]+/: Invalid escape`

Can you please check .Thanks

**Comment by ts-thomas** [comment]
I can't reproduce this error. Please open again, when the issue is still existing.
