### ISSUE TITLE
How to sort by date?

### ISSUE THREAD

**Issue by bb-in-hoodie** [nextapps-de/flexsearch#298]
It seems like there 'had been' a custom sort option once, but it's gone now.
But I cannot find a patch note relevant to it.
Is there any sort alternatives?
What I want to do is simply sort the result by 'date' field.

**Comment by budarin** [comment]
the result is the array of ids which might be converted into array of objects and then simply sort by array method sort

**Comment by bb-in-hoodie** [comment]
> the result is the array of ids which might be converted into array of objects and then simply sort by array method sort

well yes, that works for sure. And I'm doing it as an alternative already. I just wonder why the feature once exist is now gone.

**Comment by ts-thomas** [comment]
1. use document index and add objects to the index which includes a date field
2. apply search and pass option `enrich: true`
3. sort results by standard function `arr.sort(fn)` and apply the date comparison in to this sort function

**Comment by davidhq** [comment]
This means that one has to use bigger `limit` to do it right? And kind of never use the `offset` option.
