### ISSUE TITLE
TypeError C is not a function

### ISSUE THREAD

**Issue by pdhoward** [nextapps-de/flexsearch#30]
Thanks for this capability. I am excited to learn how this works for several use cases I have

I ran your 'best practice with some modeification. I cannot find the source of the error ...
"c is not a function'

Here is my code

const FlexSearch = require("flexsearch")

const bookstore = new FlexSearch();
const pizzashop = new FlexSearch();
const votingbooth = new FlexSearch();

let settings = {
    action: "score", 
    adventure: {
        encode: "extra",
        tokenize: "strict",
        depth: 5,
        threhold: 5,
        doc: {
            id: "id",
            field: ["intent", "text"]
        } },
         
    comedy: {
        encode: "advanced",
        tokenize: "forward",
        threshold: 5
    }
}
let index = {}

const add = (id, cat, intent, text) => {
    console.log(gr(`Starting on Index ${id}`))
    console.log(`for ${cat}, ${intent}, ${text}`)
    try {
        (index[cat] || (
            index[cat] = new FlexSearch(settings[cat])
        )).add(id, intent, text);
    } catch(error) {
        console.log(error)
    }
  
}

const search = (cat, query) => {
    return index[cat] ? index[cat].search(query) : [];
}

let x = 0
training.map((t) => {
    console.log(b(`Creating index ${x}`))
    x++
    add(x, "bookstore", t.intent, t.text);
    add(x, "pizzashop", t.intent, t.text);
    add(x, "votingbooth", t.intent, t.text);
})

//add(1, "action", "Movie Title");
//add(2, "adventure", "Movie Title");
//add(3, "comedy", "Movie Title");

console.log(r(`THIS SHOULD EXECUTE LAST`))
//index.update(10025, "Road Runner");
//index.remove(10025);
var result1 = search("bookstore", "i am searching for a book"); // --> [1]
var result2 = search("pizzashop", "howdy"); // --> [1]
var result3 = search("votingboooth", "i need directions"); // --> [1]

console.log(`========== FAST SEARCH TEST ==========`)
console.log(result1)
console.log(result2)
console.log(result3)

The log shows an empty array

**Comment by ts-thomas** [comment]
Hello sorry for the late answer. I do not fully understand your intend, but I can provide you a running version:

```
const FlexSearch = require("flexsearch");

// provide a document descriptor for each index
// the field "id" and at least one "field" is mandatory.

const settings = {
    "bookstore": {
        preset: "score",
        doc: {
            id: "id",
            field: ["intent", "text"]
        }
    },
    "pizzashop": {
        encode: "extra",
        tokenize: "strict",
        depth: 5,
        threshold: 5,
        doc: {
            id: "id",
            field: ["intent", "text"]
        }
    },
    "votingbooth": {
        encode: "advanced",
        tokenize: "forward",
        threshold: 5,
        doc: {
            id: "id",
            field: ["intent", "text"]
        }
    }
};

const index = {};

const add = (cat, doc) => {
    (index[cat] || (
        index[cat] = new FlexSearch(settings[cat])
    )).add(doc);
};

const search = (cat, query) => {
    return index[cat] ? index[cat].search(query) : [];
};

// provide documents which have the same structure as defined in the document descriptor above

const bookstore = [{
    id: 0,
    intent: "intent",
    text: "text"
},{
    id: 1,
    intent: "intent",
    text: "i am searching for a book"
}];

const pizzashop = [{
    id: 0,
    intent: "intent",
    text: "text"
},{
    id: 1,
    intent: "intent",
    text: "howdy"
}];

const votingbooth = [{
    id: 0,
    intent: "intent",
    text: "text"
},{
    id: 1,
    intent: "intent",
    text: "i need directions"
}];

// add a full document or an array of documents to the index

add("bookstore", bookstore);
add("pizzashop", pizzashop);
add("votingbooth", votingbooth);

// search

var result1 = search("bookstore", "i am searching for a book"); // --> [1]
var result2 = search("pizzashop", "howdy"); // --> [1]
var result3 = search("votingbooth", "i need directions"); // --> [1]

console.log(`========== FAST SEARCH TEST ==========`);
console.log(result1);
console.log(result2);
console.log(result3);
```

I hope it helps you.

**Comment by ts-thomas** [comment]
You can also skip the doc descriptor and just pass one string value with `index.add(id, string)`, but this will return just ids as a result. If that fits your needs then this is noticeably faster.

**Comment by ts-thomas** [comment]
One last thing :) the next version will provide you a "where" field in the custom search, this will replace the by-hand-category-splitting completely

**Comment by pdhoward** [comment]
Thanks much for the response ... I corrected the method as you noted above it worked beautifully!
.add(doc);   // pass in the object since I used the doc descriptor

Very excited about this search capability!
