### ISSUE TITLE
Permission request to use Flexsearch logo

### ISSUE THREAD

**Issue by bobmitro** [nextapps-de/flexsearch#302]
Dear Flexsearch Team,

I would like to use the Flexsearch logo in the plugin created for Publii CMS and on website in the upcoming plugins section (marketplace.getpublii.com). 

I will not use it in any other way besides mentioned above. Is it acceptable to you?

Thank you for your consideration and your time.

**Comment by ts-thomas** [comment]
Of course, Yes you can do.
