### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by jeffabruce** [nextapps-de/flexsearch#306]
I can't be the only one this happened to.

When I tried to download any of the flexsearch JS files, Windows Defender claimed the file as containing virus "Trojan:Script/Ulthar.A!ml".

On a different system, Defender doesn't identify it as a virus.

**Comment by jeffabruce** [comment]
I can't explain why one machine flagged and another didn't. I have run the same file through many others and only the one flagged it. So, I guess it's just a false positive on a specific system.

**Comment by ts-thomas** [comment]
You can trust me, it is not a virus.
