### ISSUE TITLE
Serialize/Deserialize for SSR ?

### ISSUE THREAD

**Issue by revskill10** [nextapps-de/flexsearch#31]
Does the library support serialize/deserialize flexsearch object as json ?
I'd love to create index in Node , but will deserialize the object in browser for client-side searching.

**Comment by ts-thomas** [comment]
https://github.com/nextapps-de/flexsearch#exportimport-index
Have you tried this?

**Comment by tmsss** [comment]
I'm trying to serialize/deserialize flexsearch object as json, but I'm getting an `TypeError: m[g] is undefined` error. Can you show us a simple working example?

**Comment by ts-thomas** [comment]
The flexsearch object (instance) itself cannot be serialized. You have to use the index methods, e.g.:

Create an index:
```js
var index = new FlexSearch();
```

Adding content:
```js
index.add(0, "Title 1");
index.add(0, "Title 2");
index.add(0, "Title 3");
```

Export index:
```js
var export = index.export();
```

The export represents a serialized string of the whole index.

Import/Restore index:
```js
index.import(export);
```

**Comment by tmsss** [comment]
Thank you for the work done and also for the answer, it already works. To learn a little more about javascript and Gatsby.js, I've created a plugin with simple implementation of Flexsearch.js [here](https://github.com/tmsss/gatsby-plugin-flexsearch). For now, it has only basic text search functionality working, but feel free to look at the code, I would be happy to learn about future improvements.
