### ISSUE TITLE
Suggestion and or operator?

### ISSUE THREAD

**Issue by NathanThomasWebDeveloper** [nextapps-de/flexsearch#310]
The link to 'suggestion' here is dead. 

https://github.com/nextapps-de/flexsearch/blob/bffb255b7904cb7f79f027faeb963ecef0a85dba/README.md?plain=1#L213

Is there some documentation that explains the impact of setting the option `suggest` to `true`? I ran into what I thought was a bug where I searched "foo'bar" it return results for both foo OR bar. I'm trying to figure out whether this is expected behaviour when `suggest` is `true`. It seemed to make it impossible to search for example for "foo's" i.e. belonging to foo! The issue is fixed if I leave `suggest'`as `false`

**Comment by ts-thomas** [comment]
Refers to this: https://github.com/nextapps-de/flexsearch/issues/327
