### ISSUE TITLE
How to add search with cyrillic and english characters at the same time using gatsby-plugin-flexsearch?

### ISSUE THREAD

**Issue by VitaliyHrabovych** [nextapps-de/flexsearch#318]
I did step by step through this guide [here](https://www.gatsbyjs.com/plugins/gatsby-plugin-flexsearch/) and search works great with eng characters but doesn't work with cyrillic.
I saw solutions for React plugin but did not for gatsby.
So, how can I add search with cyrillic in gatsby-plugin-flexsearch

### #gatsby-config.js
```
resolve: 'gatsby-plugin-flexsearch',
      options: {
        languages: ['en'],
        type: 'Mdx',
        fields: [
          {
            name: 'title',
            indexed: true, 
            resolver: 'frontmatter.title',
            store: true
          },
          {
            name: 'slug',
            indexed: false,
            resolver: 'fileAbsolutePath',
            store: true,
          }
        ]
      }
```

**Comment by ts-thomas** [comment]
Please message the author of this plugin. Sorry I cant help you.
