### ISSUE TITLE
Multiple documents update by query?

### ISSUE THREAD

**Issue by georgyfarniev** [nextapps-de/flexsearch#32]
Hello, first of all, thanks for creating new nice search engine. We are looking to use it instead of elasticsearch, which is very complex and have lots of legacy in it’s DSL and difficulties to get desired results. Currently we are interested if there’s any plans to implement multiple documents update by single query? It’s necessary, for example, to disable some of products when it’s category is disabled. 

Also, to avoid creating another ticket, I would like know if it is possible to boost search result based on numeric value stored in search index itself.

Thanks in advance.

**Comment by ts-thomas** [comment]
Hello, thanks you.

You can pass an array of documents as described here: https://github.com/nextapps-de/flexsearch#docs, that is also supported for update documents. The FlexSearch-Server is one version behind and actually do not support documents, but it will be rolled out soon with the next update.

Boost is actually limited and just apply to the score of indexed fields. Maybe the next update, which is actually in progress, could help you. It provides tagging, where-clause and custom sorting. Probably you can solve it with this new functionality.

**Comment by georgyfarniev** [comment]
@ts-thomas thanks a lot for quick and robust response. Looking forward to play with new version. This is really important project because many people struggling with overwhelmed elasticsearch api and it’s heavy resources requirements. Good luck to achieve success for this project!
