### ISSUE TITLE
 FlexSearch is not a constructor

### ISSUE THREAD

**Issue by mmm8955405** [nextapps-de/flexsearch#321]
The simplest node JS project.

var index = new FlexSearch({
    preset: "memory",
    tokenize: "forward",
    resolution: 5
});

or

var index = FlexSearch.create({
    encode: str => str.replace(/[\x00-\x7F]/g, "").split("")
});

 FlexSearch is not a constructor!!
  or
  create not find 

Is flexsearch class 
![22](https://user-images.githubusercontent.com/5687907/162161096-50045639-9bb4-4f9f-9397-ef9763634def.png)
still available in version 0.7.21?

![1](https://user-images.githubusercontent.com/5687907/162160546-ee4f1dd2-aec7-4638-ab9f-4e7d1b87e87a.png)

**Comment by mmm8955405** [comment]
I found that after 0.7.0, this constructor can no longer be used. However, versions before 0.6.32 can be used.



So how to use CJK or new after 0.7. Is this a bug or feature removal?

**Comment by mmm8955405** [comment]
After reading so much, the program you wrote has the most bugs, and it won't work according to what your document says. It's too painful

**Comment by mmm8955405** [comment]
There are so many problems even in the demo stage of the experiment.... There are too many bugs in the function than the performance. Documents will boast

**Comment by spidgorny** [comment]
```
import FlexSearch from 'flexsearch/dist/flexsearch.es5.js'
let index = new FlexSearch.FlexSearch.Index()
```

works for me
