### ISSUE TITLE
phantomjs (part of mocha-phantomjs) is officially deprecated and no longer builds on Mac

### ISSUE THREAD

**Issue by RupertBarrow** [nextapps-de/flexsearch#322]
On MacOS 11.6.4 (Big Sur), running tests for flexsearch `yarn test` causes an error due to the fact that the phantomjs executable compiled in mocha-phantomjs 4.1.0 is no longer compatible with today's architecture : 
`An error occurred trying to launch phantomjs at "/Users/.../flexsearch/test/node_modules/phantomjs/lib/phantom/bin/phantomjs": Error: spawn Unknown system error -86`

The author of mocha-phantomjs suggests to migrate to mocha-chrome : 
https://github.com/nathanboktae/mocha-phantomjs

**Comment by ts-thomas** [comment]
Tests will come back soon. Phantomjs is actually completely dropped because there is no need for ES5 support anymore.
