### ISSUE TITLE
Benchmark with algolia ?

### ISSUE THREAD

**Issue by bloodbee** [nextapps-de/flexsearch#33]
Can someone do a benchmark between this library and [Algolia](https://www.algolia.com/)?
I just want to know if I should drop algolia for a better copycat?
Thank you ;)

**Comment by ts-thomas** [comment]
It will be hard to compare a hosted full-featured service against a plain library. However, you could compare FlexSearch-Server with Algolia and use the Apache benchmark tool: https://httpd.apache.org/docs/2.4/programs/ab.html
Hint: to make a good comparison you need to initialize equal conditions of a production system on both sides.
