### ISSUE TITLE
Can prefix results be prioritised in search result order ?

### ISSUE THREAD

**Issue by TheunisKotze** [nextapps-de/flexsearch#340]
I'm trying to use flexsearch for autocomplete on a list of cities where it just about always makes sense to display the results that start with search text first. Is there a way to achieve this without running an additional sort, or should I rather use a different library ?

Eg search for "park" returns the following order:
Bellpark
Milpark
Parktown

I want Parktown to be first in the list

**Comment by ts-thomas** [comment]
Use the tokenizer `forward` as described in the documentation:

```js
const index = new Index({ tokenize: "forward" });
```

**Comment by TheunisKotze** [comment]
Thanks for the response, I was running with tokenize: forward, though using Document. Tried both of your suggestions and neither seem to work. The content is just about all single terms yea, city and suburb names.
