### ISSUE TITLE
Bug with importing encoders in node

### ISSUE THREAD

**Issue by Timpan4** [nextapps-de/flexsearch#351]
I'm getting this issue when trying to import the "advanced" encoders:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/70634109/199449932-9f4a5d34-41f7-41af-b699-c85490297e96.png">

Doesn't matter if i use import or require, the error is comming from within the package.

My code:
```js
import advanced from 'flexsearch/dist/module/lang/latin/advanced.js';

const data = new Document({
    encode: advanced,
    preset: 'match',
    tokenize: 'full',
    index: ['Key', 'Value', 'UserId', 'Name', 'ProfilePicture', 'Alerting', 'Priority', 'IsExternal'],
    store: true,
    id: 'id',
    resolution: 1,
    depth: 10
});
```

**Comment by ts-thomas** [comment]
It looks like you are using ES6-modules in Nodejs-Module-Project. Here is how to use in Node.js, please check:

https://github.com/nextapps-de/flexsearch#nodejs
