### ISSUE TITLE
🤔 Usecase: Backebd - How To

### ISSUE THREAD

**Issue by byawitz** [nextapps-de/flexsearch#381]
Hey

First, Thanks for the package it was beneficial for many projects. 

I want to be sure if this is the best way to handle flex search in a backend case.

1. I have created `flexSearch` document instance as follows:
```javascript
const document = fsearch.Document({
    tokenize: "full",
    document: {
        store: true,
        id: "flight_id",
        index: ["ticket_no", "flight_id", "fare_conditions", "amount"]
    }
});
``` 

2. Then, I iterated over 50K results from the Postgres database.
```javascript
const rows =  await sql`SELECT * FROM ticket_flights LIMIT 50000;`; // took 5 seconds

rows.forEach((row)=>{
  await document.add(row);
});
```

3. Then I added a search endpoint and returned the results as follows: 
```javascript
const res = document.search(search, 10, [
  "ticket_no", "flight_id", "fare_conditions", "amount"
]);
```

And any request being processed blazingly fast between 1-50ms.

When I tried to go up to 1,000,000 records the loading time took around 60 seconds and the search answer stayed the same.

My question is:
- Is this the right approach? 
- Up to how many documents the plugin should work with?
- When I used the 1M records the RAM usage went up to 800MB is that normal?

Thanks

**Comment by zanzlender** [comment]
Can you try how high RAM is if you put tokenize `forward`?

**Comment by byawitz** [comment]
Sure 
I've summarized it for you in a table:

| No of records | Search token type | load time | RAM | AB 5000Req |
|---------------|-------------------|-----------|-------|------------|
| 100K | Full | 7014ms | 562MB | 2498/Sec |
| 100K | Forward | 1780ms | 208MB | 2766/Sec |

**Comment by zanzlender** [comment]
Very cool to see 👍  Also, do you manage to get full enriched results back? Or do you just get the id's of the records?

Regarding your question, I do this on my backend as well. Well similar to that. And for now it seems to work... But I can't say for sure if it's really ideal...

**Comment by byawitz** [comment]
Thanks
Yes, I've used the `store:true` option.

**Comment by zanzlender** [comment]
You're a lifesaver 🥇

**Comment by ts-thomas** [comment]
It looks pretty good. The upcoming version will provide some improvements.
