### ISSUE TITLE
Is there any way I can use this library for the iife mode? 

### ISSUE THREAD

**Issue by rajasimon** [nextapps-de/flexsearch#389]
My rollup config look like this 

```
{
    input: "js/index.js",
    plugins: [
      nodeResolve(),
      babel({
        presets: ["@babel/preset-env"],
        babelHelpers: "bundled"
      }),

    ],
    context: "null",
    moduleContext: "null",
    output: {
      exports: "named",
      file: "dist/main.js",
      format: "iife",
      name: "lighterhtml"
    }
  },
```

And I wanted to use flexsearch. Does anyone know how to do that? 

So far I can include the Index it seems but that is not working as expected.

**Comment by ts-thomas** [comment]
Use the bundled versions which exports to window.FlexSearch: https://github.com/nextapps-de/flexsearch/blob/master/dist/flexsearch.bundle.js

Or check the babel configuration of Mikado build: https://github.com/nextapps-de/flexsearch/blob/master/.babelrc
