### ISSUE TITLE
Is Index data of FlexSearch persisted on transient?

### ISSUE THREAD

**Issue by chzhongsending** [nextapps-de/flexsearch#390]
Hi,  Is the Index data of FlexSearch persisted on transient?

I mean, when users refresh the page, could the user search for data added to the index in the previous session? Or should I add them to the index again before users could search?

I see the export/import API. should I use them to save/restore index data?

**Comment by ts-thomas** [comment]
> I mean, when users refresh the page, could the user search for data added to the index in the previous session?
Just when exported/imported you can restore indexes on page reload, otherwise it needs re-indexing.
