### ISSUE TITLE
flexsearch-ts/module/index.js has no Document export

### ISSUE THREAD

**Issue by xuehaizhen-ones** [nextapps-de/flexsearch#391]

**Comment by mahnunchik** [comment]
@ts-thomas  could you please make normal exports for ESM environment?

```js
import { Document } from 'flexsearch'; 
```

**Comment by ts-thomas** [comment]
What is `flexsearch-ts` ? ESM Modules are available here: https://github.com/nextapps-de/flexsearch/tree/master/dist
