### ISSUE TITLE
Please remove incorrect index.d.ts from the published package

### ISSUE THREAD

**Issue by dhdaines** [nextapps-de/flexsearch#392]
The types in `index.d.ts` are quite incorrect, whereas the third-party ones in DefinitelyTyped (`@types/flexsearch`) appear to be correct.

Unfortunately TypeScript will prefer to use the ones in the package... the advice on the internet seems to be just to downgrade FlexSearch, presumably to a version where `index.d.ts` is correct.  This seems like bad advice.

Please fix the types or simply remove them so the library can be used from TypeScript.

**Comment by dhdaines** [comment]
Note that the best workaround for the moment is to use the `paths` option in `tsconfig.json` to override the built-in types, as per https://stackoverflow.com/questions/41558661/ignore-bundled-d-ts-and-use-external-declarations  (actually I am surprised this is not a more common situation with NPM modules given their highly variable code quality):

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "flexsearch": ["node_modules/@types/flexsearch"]
    }
  }
}
```

**Comment by Theaninova** [comment]
I'm using [patches](https://github.com/Theaninova/dotio/tree/73c71836dc625d9237518739f076784b1b560a6a/patches) with [patch-package](https://www.npmjs.com/package/patch-package). Not the best solution but it works.
