### ISSUE TITLE
Flexsearch stops working when electron app is packaged

### ISSUE THREAD

**Issue by agustingroh** [nextapps-de/flexsearch#401]
I am utilizing the Flexsearch library within an Electron app written in TypeScript. The app's versions are as follows:

- Electron version: 25.2.0
- Flexsearch version: 0.7.31
- Flexsearch types version: 0.7.3
- Node version: 18.15.0

The library works fine in the development environment. When the app is packaged the library stops working.

here is how I am importing the library
`const Index = require('flexsearch');
 const index = new Index(getSearchConfig());
`

Error
`TypeError: p is not a constructor
    at i.Indexer.index `

It seems like the Indexer constructor is not being recognized, resulting in this error.

**Comment by agustingroh** [comment]
Hi @ts-thomas 
here is my configuration.
```
{
  depth: 1,
  bidirectional: 0,
  resolution: 9,
  minlength: 2,
  stemmer: getDefaultStemmer(),
}.
```
Am I missing something?

**Comment by aizotov** [comment]
What was the resolution here? Was this a valid bug that was fixed or a misconfiguration?
