### ISSUE TITLE
0.7.3 includes undocumented breaking change  / Changelog outdated

### ISSUE THREAD

**Issue by markstos** [nextapps-de/flexsearch#403]
After the Ghost project attempted to upgrade from 0.7.21 to 0.7.31, the project broke. Reverting fixed the issue. The error was:

```
search-index.js:12 Uncaught TypeError: b.Document is not a constructor
    at new cm (search-index.js:12:27)
```

To evaluate the safety of this upgrade, the Flexsearch Changelog could be consulted, but it hasn't been updated in a couple of years. 

Looking at the Github releases page, there are no notes about what changes in the 0.7.3 release:

https://github.com/nextapps-de/flexsearch/releases

Please keep either the Changelog or the Releases page up to date to users understand whether it's necessary or safe for them to upgrade or not. 

Thank  you!

**Comment by markstos** [comment]
Having more descriptive commit titles could make it easier to generate the Changelog entries or release notes. Many the recent commits now say "fix issue" with an issue number, requiring visiting 10 additional pages to get a summary of what changed recently:

![image](https://github.com/nextapps-de/flexsearch/assets/25829/5fbae953-7fae-4898-aede-b8d0c34ece49)

**Comment by ts-thomas** [comment]
@markstos could you solve the issue?
