### ISSUE TITLE
Current NPM package is stale

### ISSUE THREAD

**Issue by nickweedon** [nextapps-de/flexsearch#424]
Looks like the current source code has numerous useful fixes to critical bugs (including making export awaitable).
The current NPM package however (0.7.31) does not include these fixes and was built over a year ago.

Any chance of a new NPM package build any time soon?

Awesome library by the way (well i'm guessing it will be once i can get it work lol)!

**Comment by schalkneethling** [comment]
> Looks like the current source code has numerous useful fixes to critical bugs (including making export awaitable). The current NPM package however (0.7.31) does not include these fixes and was built over a year ago.
> 
> Any chance of a new NPM package build any time soon?
> 
> Awesome library by the way (well i'm guessing it will be once i can get it work lol)!

It looks like this is resolved now as the version is up to `0.7.43` - https://www.npmjs.com/package/flexsearch - and it shows that it was published 17 days ago.

**Comment by ts-thomas** [comment]
Should be solved. If you find any issue please open a ticket again. Thanks a lot.
