### ISSUE TITLE
Any reason for all the weird linebreaks in flexsearch.js?

### ISSUE THREAD

**Issue by samuelpath** [nextapps-de/flexsearch#43]
I say weird, but I should rather say… unconventional.

Like:

```
while(i < length){

                        tmp = arr[i++];

                        const index = "@" + tmp;

                        if(check[index]){
```

Are they on purpose?

If so, what is their purpose?

If not, could using tools like Prettier (or Prettier + ESLint) help?

**Comment by ts-thomas** [comment]
Unconventional measured on which convention? Sadly there is no ultimate convention. And one of them I follow is that between a declaration of a new variable (const index ...) is a blank line. That's all.

**Comment by ts-thomas** [comment]
By the way I use app.codacy.com with almost every option enabled.
