### ISSUE TITLE
Error while loading language files on node.js

### ISSUE THREAD

**Issue by tmsss** [nextapps-de/flexsearch#45]
I'm trying to load the language files to use with the stemmer p.e., but I'm getting a `TypeError: Cannot read property 'registerLanguage' of undefined` error.

```
var FlexSearch = require('flexsearch')
require(require('flexsearch/lang/en')
```
The error seems to indicate that the flexsearch object is not in scope, but when pass it as a global variable I get the same error.  Am I missing something here?

**Comment by ts-thomas** [comment]
That's true, is it a bug. Will be fixed at least in the next version. What you can do alternatively is a simple quick-fix:

1. copy & paste the code from the language pack below the require('flexsearch')
2. replace this line:

```js
root["FlexSearch"]["registerLanguage"]("en", {
```

into this:

```js
FlexSearch.registerLanguage("en", {
```

**Comment by tmsss** [comment]
Thank you for the answer, your quick fix works.
