### ISSUE TITLE
Error on compile.js

### ISSUE THREAD

**Issue by KyoungHwanLee** [nextapps-de/flexsearch#46]
I tried to build this library with 'npm run build-compact' and got some errors like below :

`/bin/sh: -c: line 0: unexpected EOF while looking for matching ''
/bin/sh: -c: line 1: syntax error: unexpected end of file
{ Error: Command failed: java -jar node_modules/google-closure-compiler-java/compiler.jar --compilation_level=ADVANCED_OPTIMIZATIONS --use_types_for_optimization=true --new_type_inf=true --jscomp_warning=newCheckTypes --generate_exports=true --export_local_property_definitions=true --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT6_STRICT --process_closure_primitives=true --summary_detail_level=3 --warning_level=VERBOSE --emit_use_strict=true --output_manifest=log/manifest.log --output_module_dependencies=log/module_dependencies.log --property_renaming_report=log/renaming_report.log' --js='flexsearch.js' --js='lang/**.js' --js='!lang/**.min.js' --define='RELEASE=compact' --define='DEBUG=false' --define='PROFILER=false' --define='SUPPORT_WORKER=false' --define='SUPPORT_ENCODER=true' --define='SUPPORT_CACHE=false' --define='SUPPORT_ASYNC=true' --define='SUPPORT_PRESETS=true' --define='SUPPORT_SUGGESTIONS=false' --define='SUPPORT_SERIALIZE=false' --define='SUPPORT_INFO=false' --define='SUPPORT_DOCUMENTS=true' --define='SUPPORT_WHERE=false' --define='SUPPORT_LANG_DE=false' --define='SUPPORT_LANG_EN=false' --js_output_file='dist/flexsearch.compact.js' && exit 0`

and just found a simple error in 'compile.js(116:92)'.

`    exec("java -jar node_modules/google-closure-compiler-java/compiler.jar" + parameter + "' --js='flexsearch.js' --js='lang/**.js' --js='!lang/**.min.js'" + flag_str + " --js_output_file='dist/flex
search." + (options["RELEASE"] || "custom") + ".js' && exit 0", function(){
`

After removing the unnecessary single quotation after `parameter + "`, the build process worked fine.
I think it's just a mistyping... maybe. 😓

**Comment by ts-thomas** [comment]
Thanks for the report. That's true, this quotation is not right. I'm wonder that this did not produce an error on my side. Will be fixed in next version.
