### ISSUE TITLE
Funding?

### ISSUE THREAD

**Issue by georgyfarniev** [nextapps-de/flexsearch#47]
Idea: implement funding of this project using something like [issuehunt](https://issuehunt.io/)

**Comment by ts-thomas** [comment]
Thanks for your suggestion. We from Nextapps are still planning a financial strategy. Next week, a bigger meeting is planned for this purpose. Funding of course is one of many possibilities we will talk about.

**Comment by ts-thomas** [comment]
This week we will plan the strategy to provide a solid and extendable open source software. The __Plugin API__ is one of the key features we will talk about and it is also a requirement for most upcoming contributions.
