### ISSUE TITLE
Exception thrown when searching for a value containing whitespace where suggest is set to true

### ISSUE THREAD

**Issue by mawiza** [nextapps-de/flexsearch#48]
Hi Thomas

Using the following example

```
const FlexSearch = require('./flexsearch')

const fs = new FlexSearch({
  encode: 'extra',
  tokenize: 'full',
  threshold: 1,
  depth: 4,
  resolution: 9,
  async: false,
  worker: 1,
  cache: true,
  suggest: true,
  doc: {
    id: 'id',
    field: [ 'intent', 'text' ]
  }
})

fs.add([
  {
    id: 0,
    intent: 'intent',
    text: 'text'
  }, {
    id: 1,
    intent: 'intent',
    text: 'howdy - how are you doing'
  }
])

console.log('INFO', fs.info())

const result = fs.search('howdy', { bool: 'or' })
console.log('RESULT', result)

const result2 = fs.search('howdy -', { bool: 'or' })
console.log('RESULT', result2)

```

An exception is thrown using `'howdy -` as search parameter. When setting suggest to false, the search is successful, but the search for `howdy -` does not find any results.

The exception thrown is

```
.../search/flexsearch.js:3308
                    z = suggestions.length;
                                    ^

TypeError: Cannot read property 'length' of undefined
    at intersect (.../servers/search/flexsearch.js:3308:37)
    at FlexSearch.merge_and_sort (.../servers/search/flexsearch.js:1393:22)
    at FlexSearch.search (.../servers/search/flexsearch.js:1561:43)
    at Object.<anonymous> (.../servers/search/test2.js:33:19)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
```

In flexsearch on line 3068
```
function intersect(arrays, limit, cursor, suggest, bool, has_not) {

            let result = [];
            let suggestions;
            const length_z = arrays.length;
```
suggestions is not being assigned, because the while loop on line 3133 is false

```
while(++z < length_z){

``` 
so the assignment of the suggestion variable on line 3211 is bypassed

```
                    let found = false;

                    i = 0;
                    suggestions = [];

                    while(i < length){
```

The reason the search for `howdy -`, when suggestions is false, is unsuccessful is probably because of the options passed in. Should I implement my own tokenizer if I would like to find queries like `howdy -`?
 
Thanks in advance

Regards
William

**Comment by ts-thomas** [comment]
Thanks a lot for the report. This seems to be a bug of the suggestion-feature. Passing `suggest: false` does not produce this bug. The fix will be deployed in the next version.

**Comment by ts-thomas** [comment]
_Should I implement my own tokenizer if I would like to find queries like `howdy -`?_

These based on a second bug. For some reason passing `depth: 4` produce it here. Although the contextual index just support `tokenizer: "strict"`, so theoretically the `depth` should not have any relevant meaning. You can simply remove the `depth`. This issue will be also fixed in the next version.

**Comment by mawiza** [comment]
You're welcome and thank you for the feedback.
