### ISSUE TITLE
Development Roadmap (Please Participate)

### ISSUE THREAD

**Issue by ts-thomas** [nextapps-de/flexsearch#49]
Please make suggestions or give some feedback.

## 1. Extract Core Functionality
The extraction of the core functionality is basically required for many upcoming features as well as for still existing ones, like:
- Plugin API
- Custom Tooling
- Language-specific ports or migrations
- Pluggable Workflows
- All kinds of extensions

These still existing features has to remain as a core functionality:
1. Lexical Pre-Scored Index
2. Contextual-based Map
3. Index-related Settings:
    - threshold
    - resolution
    - depth
    - rtl
4. Matching Tokens (Query)
5. Cursor-based Pagination
6. Logical Operators
7. Cross-Process Intersection
8. Index-based Suggestions

The basic core API should have this methods:
1. create
2. init
3. add
4. update
5. remove
6. destroy
7. match (search)

These missing features also needs to be integrated as a core functionality:
- Providing abstract I/O, supporting various kinds of index storage:
  - In-Memory
  - Partial Persistent Storage (persistent documents, in-memory index)
  - Storage-only (persistent documents, persistent index)

These functions should be extracted as an optional tooling:
- System-specific Features (Browser, Node.js):
  - Web Worker
  - Async
- Language-specific Features:
  - Encoder
  - Tokenizer
  - Matcher, Stemmer, Filter
- Documents (Field-Search)
- Custom Search
- Find / Where / Tags
- Export / Import (Serialization)
- Cache
- Presets

## 2. Plugin API
The plugin API is required to provide additional tooling and features in a modular and extendable manner. The plugin API should have these capabilities:
1. Extend via ad hoc methods
2. Extend via pipeline
3. Extend via events (callbacks)
4. Plugin Package Descriptor

## 3. Prerequisites
1. Extract language-specific logic
2. Provide process connectivity and refactor

## 4. Language Port
There are several requests of a TypeScript port. The advantage of TypeScript compared to plain JavaScript may be too less, since the TypeScript also compiles to JavaScript and is also less optimized as the Google Closure Compiler for that purpose. 

Technically there are two targets:

1. Browser
2. System (OS)

Browsers are actually covered as well as Node.js. Making a TypeScript port will do not cover any additional ecosystem. Only the formal codebase will differ and at the end it is just a different pattern for the same result. That's why I prefer a browser-less system-wide port over TypeScript. The language ___Rust___ is pretty close to TypeScript/JavaScript and covers 2., so this might be a better candidate for a port.

There is no final decision at the moment, so let us discuss pro and cons here.

**Comment by paul-go** [comment]
AssemblyScript may be an option if you're looking to move to a WebAssembly platform, but don't want to stray from the JavaScript / TypeScript mindset.

**Comment by ScreamZ** [comment]
At least u can make typescript ambient types for user to get completion

**Comment by RXminuS** [comment]
I don't think anyone has asked for a typescript port. I think people just want a types.d.ts file. I'll see if I have time today but otherwise I can put up a bounty.

**Comment by ts-thomas** [comment]
Personally, I would prefer Rust for a full port. I've made some basic implementation tests and it feels right out of the box and also has an incredible performance.

Currently I am working on the completion of 3 local feature branches:
1. Provide a field "store" in document descriptor to select fields from a document which should be stored (separates storing from indexing)
2. Remove Where-clause, this feature feels just bad and also performs like that (most of features are also covered by using Tags)
3. Re-implement Tags, there is much more potential by using tags

There will come very soon.

**Comment by RXminuS** [comment]
@ts-thomas do you want to push these feature branches, or create a draft 0.7.0 branch? Would love to help (specifically for field boosting) but not sure what is going on atm. That also has the benefit of showing the progress and helping people extrapolate when new feature requests will land.

W.r.t. to a full rewrite in Rust...I know there's things like elasticlunr-rs that have done a partial port of that project. But unless we're doing a full rewrite I think it would make sense to at least finish the 0.7.0 version as is so that there's a solid base before venturing out into a "rexsearch".
