### ISSUE TITLE
How to create an index for a book

### ISSUE THREAD

**Issue by aharonNF** [nextapps-de/flexsearch#52]
Hey
First thanks for the amazing library!

I would like to know if you can index a number and get the subject name, sub-topic, and paragraph number.
And whether it is possible to find two paragraphs together
For example
```
book:
[
    {
        "topic": "topic",
        "content": [
            {
                "title":
                "parts": [
                    "word1, word2, word3, word4, word5",
                    "word6, word7, word8, word9, word10",
                ]
            }
        ]
    }
]

index.search("word2 word3") // = [{topic: "topic1", title: "title1", part: 0}]
index.search("word5 word6") // = [{topic: "topic1", title: "title1", part: 0}, {topic: "topic1", title: "title1", part: 0}]
``` 

Thanks

**Comment by ts-thomas** [comment]
Hello. Yes it is possible. I will provide you an example later today. In the meanwhile you can read here more about indexing documents: https://github.com/nextapps-de/flexsearch/blob/master/README.md#docs

**Comment by ts-thomas** [comment]
Hey, sorry for the late answer.

I made some little modifications on the document structure to solve it. Every part of a book needs its own entry as well an ID (I used a combination of ISBN and the index of part). At the end your book(s) looks like this:

```js
var books = [{
    "isbn": "978-3-86680-192-1/0",
    "topic": "topic",
    "content": {
        "title": "title",
        "part": "word1, word2, word3, word4, word5"
    }
},{
    "isbn": "978-3-86680-192-1/1",
    "topic": "topic",
    "content": {
        "title": "title",
        "part": "word6, word7, word8, word9, word10"
    }
}];
```

Create the index:
```js
var index = new FlexSearch({
    doc: {
        id: "isbn",
        field: ["topic", "content:title", "content:part"]
    }
});
```

Add books:
```js
index.add(books);
```

Search:
```js
var results = index.search("word2 word3");
```

```js
var results = index.search("word5 word6");
```

There is also a feature request here: #41 (enables the aggregation of results) that also should be interesting for this purpose.
