### ISSUE TITLE
FuzzySearch and more usage examples

### ISSUE THREAD

**Issue by xcartmods** [nextapps-de/flexsearch#56]
Hi, I've been using - https://github.com/jeancroy/FuzzySearch
...which I've found to be very quick. How does FuzzySearch compare to flexsearch?

Be great if you could make some more usage examples.

**Comment by ts-thomas** [comment]
comparison: https://raw.githack.com/nextapps-de/flexsearch/master/test/benchmark.html
On my test FlexSearch is round about 70,000 times faster.
