### ISSUE TITLE
Question on 0.7.0/Field boosting

### ISSUE THREAD

**Issue by TehShrike** [nextapps-de/flexsearch#57]
I see the documentation on indexing different fields in a document has been fleshed out, which is great, I was wondering how that would work.

The readme claims that field searching is a thing in 0.7.0, but the changelog only goes up to 0.6.0 and the version on npm is 0.6.2 – what's the deal there?

Besides wondering where I could find 0.7.0 I have one question: how does boosting work?

I have a document with a `title`, and a `body`.  I want matches in the `title` to count towards the score 10x more than matches in the `body`.

Could I achieve that by setting the boost on the `title` field to 10, and the boost on the `body` field to 1?  Is that how boost works, or have I misguessed?  What is the default boost for a field?

**Comment by ts-thomas** [comment]
Hello. Field-Search is already available. Just boosting specific fields will come in the next version which will be 0.7.0

**Comment by georgyfarniev** [comment]
Also, would be great to have boosting by **value** of  **numeric** field stored in document. For example, it's useful to sort products by categories with different priority.

**Comment by ts-thomas** [comment]
I have thought about it once again. There are two types of sorting:

1. sort by score
2. sort by field value

Basically 1. and 2. are already available. For 2. there are also customization available. A way how to customize the sort by score is actually missing. This could be done by manipulate the scoring calculation, e.g.:

1. boost score by a custom multiplier (per field, comes in v0.7.0)
2. boost score by query elevation (sponsored search)
3. adjust score by feedback (makes sorting by popularity)
4. calculate score by a custom function (when indexing)

Your example "sort by a dynamic field value" (e.g. priority) may already be possible with a <a href="https://github.com/nextapps-de/flexsearch#custom-sort">custom sorting</a>, in addition the custom function at 4. can be used to pre-score per field value (e.g. priority). When 1. and 4. are final we need to check if we can find an example, which is not covered by the available features.

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot. Support for a custom "boost" function will be available soon.
