### ISSUE TITLE
Settings get overriden

### ISSUE THREAD

**Issue by PascalSenn** [nextapps-de/flexsearch#61]
We use flexsearch in a react app. Performs pretty well, thanks! 
We store the flexsearch settings in a constant outside of a component. We also store documents and not key values pairs. 
The first initialization of the component works perfect. All following behave wrong. The doc property is null. I guess flexsearch accesses the object by reference and somehow replaces the doc property. 
![image](https://user-images.githubusercontent.com/14233220/53886432-50c91f80-4020-11e9-94b5-9790648322cb.png)
Is this behavior expected?

**Comment by ts-thomas** [comment]
Thanks for the report. You are right, the doc config will be assigned as reference. I will provide a fix shortly.

**Comment by ts-thomas** [comment]
This issue should be now fixed.
