### ISSUE TITLE
v0.6.21 TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by mahnunchik** [nextapps-de/flexsearch#64]
Hello,

I've faced with the error: `TypeError: Cannot convert object to primitive value`

It is produced in the `.add` method.

Version: 0.6.21

Version 0.6.2 works as expected.

**Comment by ts-thomas** [comment]
@mahnunchik Thanks for the report. Could you provide me the used configuration or a short example please?

**Comment by mahnunchik** [comment]
Hi @ts-thomas 

```js

import FlexSearch from 'flexsearch';
import waypoints from './data/waypoints';

const index = new FlexSearch({
  doc: {
    id: "code",
    field: {
      code: {
        split: /\s+/,
        tokenize: "strict",
      },
      title: {
        split: /[\s()-]+/,
        tokenize: "forward",
      },
    },
  },
});

//console.time('index');
index.add(waypoints);
//console.timeEnd('index');

export default index;
```

Data: https://gist.github.com/mahnunchik/6920a1039a3da4ef22177521a800642d

**Comment by ts-thomas** [comment]
@mahnunchik Sorry for the late answer. The issue here was the split-field needs a string value (to keep json compatibility):

```js
const index = new FlexSearch({
  doc: {
    id: "code",
    field: {
      code: {
        split: "/\s+/",
        tokenize: "strict",
      },
      title: {
        split: "/[\s()-]+/",
        tokenize: "forward",
      },
    },
  },
});
```

**Comment by mahnunchik** [comment]
@ts-thomas it would be more predictable to have usual regexp in normal js configuration, not a string of js regexp. Or support both formats.

**Comment by ts-thomas** [comment]
Supporting both formats is possible. The doc configuration needs a way to keep JSON standard compatibility.

**Comment by mahnunchik** [comment]
Hi @ts-thomas 

It seems `"/\s+/"` from your comment not works as expected in `0.6.22`.

**Comment by wamir79** [comment]
doesn't work for me as well. the content.split(this.split) not works as this.split is just a string and not regex.
if i use regex in the field definition the clone_object is not working correctly:
clone_object({a:/a/}) = {a:{}}

**Comment by wamir79** [comment]
patch to clone_object:

			function clone_object(obj) {
				const clone = create_object();

				for (const key in obj) {
					if (obj.hasOwnProperty(key)) {
						const value = obj[key];

						if (is_array(value)) {
							clone[key] = value.slice(0);
						} else if (value instanceof RegExp) {
							clone[key] = value;
						} else if (is_object(value)) {
							clone[key] = clone_object(value);
						} else {
							clone[key] = value;
						}
					}
				}

				return clone;
			}

**Comment by ts-thomas** [comment]
@wamir79 thanks for providing a fix.

**Comment by mahnunchik** [comment]
Should this issue be closed?

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x which solves that issue, thanks a lot.
