### ISSUE TITLE
Error when search "john wick" on demo site

### ISSUE THREAD

**Issue by trananhmanh89** [nextapps-de/flexsearch#65]
Hi,
Your work is great.

After playing around, i found an issue with your demo.

Search string "john wi" is shown fine.
But search "john wic" is empty.

Could you check it?

![2019-03-12_215239](https://user-images.githubusercontent.com/20571336/54209889-1e805c00-4511-11e9-872b-78ac79aafcf3.png)

**Comment by wingc-china** [comment]
even more interesting, using 'john wik' can find the movie though.

**Comment by trananhmanh89** [comment]
> even more interesting, using 'john wik' can find the movie though.

that's why i likes flexsearch

**Comment by ts-thomas** [comment]
This issue was fixed in v0.6.22
