### ISSUE TITLE
Relevance: can it be based on number of times a term occurs?

### ISSUE THREAD

**Issue by TehShrike** [nextapps-de/flexsearch#66]
I would expect that if I search for a term, and that term appears once in document A but several times in document B, that B would have a higher position in the results than A.  But that does not seem to be the case.

Example:

```js
const FlexSearch = require(`flexsearch`)

const index = new FlexSearch({
	tokenize: `strict`,
	encode: `advanced`,
	cache: false,
	doc: {
		id: `id`,
		field: {
			content: {
				threshold: 9,
				resolution: 10,
			},
		},
	},
})

index.add([{
	id: 1,
	content: `billy bob thorton`,
}, {
	id: 2,
	content: `billy who now what billy okay so what now thorton?`,
}])

console.log(
	index.search(`billy`)
)
// => [ { id: 1, content: 'billy bob thorton' },
//  { id: 2,
//    content: 'billy who now what billy okay so what now thorton?' } ]
```

I would expect that a search for `billy` would have a higher score for document id 2 than document id 1, but the search returns document id 1 as the top result.

Tested with flexsearch@0.6.21.

**Comment by ts-thomas** [comment]
Unfortunately this isn't supported yet. I will add a custom "boost" function where you can boost relevance accordingly to the occurrences.

**Comment by ts-thomas** [comment]
A solution could be found here: #236
