### ISSUE TITLE
Contextual scoring doesn't seem to be working

### ISSUE THREAD

**Issue by TehShrike** [nextapps-de/flexsearch#67]
When I set a `depth`, I would expect that if I search for multiple terms, documents that contain those terms near each other would score higher.

Example:

```js
const FlexSearch = require(`flexsearch`)

const index = new FlexSearch({
	tokenize: `strict`,
	encode: `advanced`,
	cache: false,
	doc: {
		id: `id`,
		field: {
			content: {
				threshold: 9,
				resolution: 10,
				depth: 2,
			},
		},
	},
})

index.add([{
	id: 1,
	content: `billy who now what billy okay so what now thorton?`,
}, {
	id: 2,
	content: `billy bob thorton`,
}])

console.log(
	index.search(`billy thorton`)
)
// => [ { id: 1,
//    content: 'billy who now what billy okay so what now thorton?' },
//  { id: 2, content: 'billy bob thorton' } ]
```

I would expect document id 2 to be the top result, since it contains "billy" and "thorton" within two words of each other, but the top result is actually document id 1.

Tested in flexsearch@0.6.21.

**Comment by ts-thomas** [comment]
This is an issue when using custom options per field. Also the ___treshold___ was too close to the ___resolution___ (when you want to get at least both entries in result). I also raised the ___depth___ to make the context bigger.

This configuration will work:

```js
const index = new FlexSearch({
    tokenize: `strict`,
    encode: `advanced`,
    cache: false,
    threshold: 5,
    resolution: 10,
    depth: 5,
    doc: {
        id: `id`,
        field: `content`
    }
});
```

I will provide a fix for the custom options per field as soon as possible.

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
