### ISSUE TITLE
Serializing as stream instead of string

### ISSUE THREAD

**Issue by stefandesu** [nextapps-de/flexsearch#68]
I'm trying to create an index over a large dataset and I want to separate the script that's creating the index from the script that's using the index. The index creation seems to work very well, but when I use `index.export()`, I'm getting a `RangeError: Invalid string length` error. Is there a way to export the index as a file without getting this error? A possible solution would be to allow exporting via a stream that could be written to a file directly.

Thanks!

**Comment by ts-thomas** [comment]
@stefandesu Thanks for the report. FlexSearch will get an update soon including support for Node.js native serialization capabilities.

**Comment by stefandesu** [comment]
@ts-thomas Thanks for the quick reply! I'm currently using FlexSearch in Node.js. Glad to hear that native serialization capabilities will be supported soon. After posting the issue, I helped myself by adding an option to export the `payload` array instead of stringifying it, but a proper implementation would be better of course. The exported file is about 1.5 GB in size, currently I'm not even sure if our virtual machines can deal with that index in memory. 😅

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.

**Comment by s-a** [comment]
Same problem here. @stefandesu can you help out how u worked around it? And hows your experience about the virtual machines memory management?

**Comment by stefandesu** [comment]
@s-a To be honest, I was just testing out Flexsearch and decided it was not the right choice, so I'm not able to find my workaround anymore. 😕 I feel like this was fixed with version >= 0.7.x though, wasn't it?
