### ISSUE TITLE
React Component? 

### ISSUE THREAD

**Issue by collegeimprovements** [nextapps-de/flexsearch#7]
Is there any plan to make a React Component from `flexsearch` ?

**Comment by ts-thomas** [comment]
Hi. Thanks for your suggestion. Currently, direct support for React components is not planned. Flexsearch is a micro library whose complexity we want to keep as low as possible in the core. However, we are already considering an auto-complete plugin for which there may be support for template or component based libraries like React, Angular, Polymer and/or HTLM5 web components.

**Comment by collegeimprovements** [comment]
Thanks for the reply :) It's great.
