### ISSUE TITLE
Search results depend on the order of fields

### ISSUE THREAD

**Issue by stefandesu** [nextapps-de/flexsearch#70]
**NOTE: I've rewritten the entire issue because I've found a way to reproduce my issue on a very small dataset.**

I've noticed that I'm missing search results depending on the order of fields that I provide when creating the index. 

In the following example, there are two objects where `notation:0` matches the search term `WW 8840`, and one object where `prefLabel:de` matches `WW 8840`. In the first example, only the latter object is returned as a search result even though all fields are supposed to be searched. The second example returns the correct search results just by reordering the fields (putting `notation:0` to the end). Note that when specifying `notation:0` as the only field to search, it will return the correct results in both cases.

Non-working example (prints `1` and `2` even though the first query should return `3` results):

```javascript
const FlexSearch = require("flexsearch")

let index = new FlexSearch({
  doc: {
    id: "uri",
    field: [
      "prefLabel:de",
      "notation",
      "editorialNote:de",
    ]
  },
  profile: "score"
})

// Example dataset
let concepts = [
  {"@context":"https://gbv.github.io/jskos/context.json","broader":[{"uri":"http://rvk.uni-regensburg.de/nt/WW%208720%20-%20WW%209239"}],"created":"2012-07-05","editorialNote":{"de":"(Blutgruppen s. XD 3200)"},"http://www.w3.org/2004/02/skos/core#closeMatch":[{"uri":"http://d-nb.info/gnd/4130604-1"},{"uri":"http://d-nb.info/gnd/4022814-9"},{"uri":"http://d-nb.info/gnd/4070945-0"},{"uri":"http://d-nb.info/gnd/4074195-3"}],"identifier":["152145:13422"],"inScheme":[{"uri":"http://uri.gbv.de/terminology/rvk/"}],"modified":"2018-12-14","notation":"WW 8840 - WW 8879","prefLabel":{"de":"Blutkörperchen (Erythrozyt, Leukozyt), Hämoglobin"},"type":["http://www.w3.org/2004/02/skos/core#Concept"],"uri":"http://rvk.uni-regensburg.de/nt/WW%208840%20-%20WW%208879"},
  {"@context":"https://gbv.github.io/jskos/context.json","broader":[{"uri":"http://rvk.uni-regensburg.de/nt/WD%205000%20-%20WD%205970"}],"created":"2012-07-05","editorialNote":{"de":"(Antibiotika s. XI 3500)"},"http://www.w3.org/2004/02/skos/core#closeMatch":[{"uri":"http://d-nb.info/gnd/4155845-5"},{"uri":"http://d-nb.info/gnd/4276935-8"},{"uri":"http://d-nb.info/gnd/4176522-9"},{"uri":"http://d-nb.info/gnd/4175383-5"},{"uri":"http://d-nb.info/gnd/4148701-1"}],"identifier":["148204:"],"inScheme":[{"uri":"http://uri.gbv.de/terminology/rvk/"}],"modified":"2018-12-14","notation":"WD 5380","prefLabel":{"de":"Pyrrolfarbstoffe, Cytochrome, Chromoproteine (Hämoglobin s. WW 8840)"},"type":["http://www.w3.org/2004/02/skos/core#Concept"],"uri":"http://rvk.uni-regensburg.de/nt/WD%205380"},
  {"@context":"https://gbv.github.io/jskos/context.json","broader":[{"uri":"http://rvk.uni-regensburg.de/nt/WW%208840%20-%20WW%208879"}],"created":"2012-07-05","editorialNote":{},"identifier":["152145:13423"],"inScheme":[{"uri":"http://uri.gbv.de/terminology/rvk/"}],"modified":"2018-12-14","notation":"WW 8840","prefLabel":{"de":"Allgemeines"},"type":["http://www.w3.org/2004/02/skos/core#Concept"],"uri":"http://rvk.uni-regensburg.de/nt/WW%208840"}
]

index.add(concepts)

let results
results = index.search("WW 8840")
console.log(results.length) // only matches the second concept (which mentions "WW 8840" in label)

results = index.search("WW 8840", {
  field: "notation"
})
console.log(results.length) // correctly matches two concepts
// with large dataset, also correctly matches the two concepts
```

Working example (prints `3` and `2` as expected, just by reordering fields):

```javascript
const FlexSearch = require("flexsearch")

let index = new FlexSearch({
  doc: {
    id: "uri",
    field: [
      "prefLabel:de",
      "editorialNote:de",
      "notation",
    ]
  },
  profile: "score"
})

// Example dataset
let concepts = [
  {"@context":"https://gbv.github.io/jskos/context.json","broader":[{"uri":"http://rvk.uni-regensburg.de/nt/WW%208720%20-%20WW%209239"}],"created":"2012-07-05","editorialNote":{"de":"(Blutgruppen s. XD 3200)"},"http://www.w3.org/2004/02/skos/core#closeMatch":[{"uri":"http://d-nb.info/gnd/4130604-1"},{"uri":"http://d-nb.info/gnd/4022814-9"},{"uri":"http://d-nb.info/gnd/4070945-0"},{"uri":"http://d-nb.info/gnd/4074195-3"}],"identifier":["152145:13422"],"inScheme":[{"uri":"http://uri.gbv.de/terminology/rvk/"}],"modified":"2018-12-14","notation":"WW 8840 - WW 8879","prefLabel":{"de":"Blutkörperchen (Erythrozyt, Leukozyt), Hämoglobin"},"type":["http://www.w3.org/2004/02/skos/core#Concept"],"uri":"http://rvk.uni-regensburg.de/nt/WW%208840%20-%20WW%208879"},
  {"@context":"https://gbv.github.io/jskos/context.json","broader":[{"uri":"http://rvk.uni-regensburg.de/nt/WD%205000%20-%20WD%205970"}],"created":"2012-07-05","editorialNote":{"de":"(Antibiotika s. XI 3500)"},"http://www.w3.org/2004/02/skos/core#closeMatch":[{"uri":"http://d-nb.info/gnd/4155845-5"},{"uri":"http://d-nb.info/gnd/4276935-8"},{"uri":"http://d-nb.info/gnd/4176522-9"},{"uri":"http://d-nb.info/gnd/4175383-5"},{"uri":"http://d-nb.info/gnd/4148701-1"}],"identifier":["148204:"],"inScheme":[{"uri":"http://uri.gbv.de/terminology/rvk/"}],"modified":"2018-12-14","notation":"WD 5380","prefLabel":{"de":"Pyrrolfarbstoffe, Cytochrome, Chromoproteine (Hämoglobin s. WW 8840)"},"type":["http://www.w3.org/2004/02/skos/core#Concept"],"uri":"http://rvk.uni-regensburg.de/nt/WD%205380"},
  {"@context":"https://gbv.github.io/jskos/context.json","broader":[{"uri":"http://rvk.uni-regensburg.de/nt/WW%208840%20-%20WW%208879"}],"created":"2012-07-05","editorialNote":{},"identifier":["152145:13423"],"inScheme":[{"uri":"http://uri.gbv.de/terminology/rvk/"}],"modified":"2018-12-14","notation":"WW 8840","prefLabel":{"de":"Allgemeines"},"type":["http://www.w3.org/2004/02/skos/core#Concept"],"uri":"http://rvk.uni-regensburg.de/nt/WW%208840"}
]

index.add(concepts)

let results
results = index.search("WW 8840")
console.log(results.length) // only matches the second concept (which mentions "WW 8840" in label)

results = index.search("WW 8840", {
  field: "notation"
})
console.log(results.length) // correctly matches two concepts
// with large dataset, also correctly matches the two concepts
```

Any idea why this is happening? Thanks!

**Comment by stefandesu** [comment]
I also encountered other problems which occur when importing large datasets into an index (thus the original title until I discovered that it was unrelated to the size of the dataset), but splitting the index into many smaller indexes seemed to alleviate those problems (and it's still plenty fast!).

**Comment by ts-thomas** [comment]
@stefandesu The issue occurs by using `"notation:0` in the field description. Actually array field notation is not supported. But this looks very easy to implement.

To solve this actually you need to serialize the array notation into a string when adding:

```js
let index = new FlexSearch({
  doc: {
    id: "uri",
    field: [
      "prefLabel:de",
      "editorialNote:de",
      "scopeNote:de",
      "notation"
    ]
  },
  profile: "score"
});
```
Either:

__simple array__
```js
concepts.forEach(function(item){ 
    item.notation = item.notation.join(" "); 
});
```

Or:

__complex array_
```js
concepts.forEach(function(item){ 
    item.notation = JSON.stringify(item.notation); 
});
```

**Comment by stefandesu** [comment]
@ts-thomas Thanks for your reply, but I think you are wrong. I updated the example above to use a string instead of the array notation (just like you suggested) and it's still happening. Also, you said "array index notation is not supported", but it did work with `notation:0` when it was last in the `field` array.

Please try the code out. I'm able to reproduce the issue on both my work computer and my personal computer. (I also used `./flexsearch/flexsearch` for the import initially because I was using a fork, but I updated that as well. Sorry about that.)

**Comment by stefandesu** [comment]
Note that this is still an issue as of FlexSearch 0.6.22 and it's preventing me from giving FlexSearch a serious go for our project. If needed, I can try to provide a PR with tests that demonstrate the problem using a simpler dataset than above.

**Comment by jay1337** [comment]
In fact, only the results with the first matching field are returned. If you search `"blue"` with indexed fields `["a", "b", "c"]` in `[{ id: "1", a:"green", b:"blue", c:"yellow"}, {id: "2", a:"orange", b:"black", c:"blue"}]` you will get only the first item since the first matching field is `"b"` and second item field `"b"` doesn't match the query.

`result[count++] = tmp;` should be added to this line https://github.com/nextapps-de/flexsearch/blob/a4e6e672a575ad3ffa003156208e4a8ebaffa46a/flexsearch.js#L3473

**Comment by stefandesu** [comment]
@jay1337 I could not reproduce the issue with your example, but I found out that adding another field to the index (even if that field does not exist in the data) makes it fail:

```javascript
const FlexSearch = require("flexsearch")

const indexSuccess = new FlexSearch({
  doc: {
    id: "id",
    field: [
      "a",
      "b",
      "c",
    ]
  },
})
const indexFail = new FlexSearch({
  doc: {
    id: "id",
    field: [
      "a",
      "b",
      "c",
      "d",
    ]
  },
})

const data = [
  { id: "1", a: "green", b: "blue", c: "yellow" },
  { id: "2", a: "orange", b: "black", c: "blue" },
]

indexSuccess.add(data)
indexFail.add(data)

let results

results = indexSuccess.search("blue")
console.log(results)
// Prints out two results as expected.

results = indexFail.search("blue")
console.log(results)
// Prints only one result -> bug!
```

Unfortunately, adding your fix doesn't change this, so the bug must be somewhere else.

In addition to that, I found out that if you try to index a field that is not available on all items in the data, FlexSearch will throw an error. I created a new issue for this: #122

**Comment by lludol** [comment]
I have the same bug!

To reproduce create documents with multiple attributes.
In the search fields put every attributes.

Then put almost the same data in two differents attributes for 3-4 documents.

Exemple
```
{ id: 1, name: 'fooA', name2: 'fooA456' }
{ id: 1, name: 'fooA', name2: 'fooA456' }
{ id: 1, name: 'fooA', name2: 'fooA456' }

{ id: 1, name: 'fooE', name2: 'fooA123' }
{ id: 1, name: 'fooF', name2: 'fooA123' }
{ id: 1, name: 'fooG', name2: 'fooA123' }
```

Now you can type in your search something like this: `fooA`
You will only get the first block (the 3 elements in my example).

I have the same bug in production but with more data!
Now I am fucked...

**Comment by JankoDedic** [comment]
Happens to me as well. When the first field matches, the following ones aren't considered at all.

**Comment by stefandesu** [comment]
I just updated my original issue so that it can be executed with version 0.6.32. Unfortunately, I wasn't able to get Flexsearch running at all with the upcoming version 0.7.0 in Node: "ReferenceError: window is not defined"

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x which solves that issue, thanks a lot.
