### ISSUE TITLE
How to know total number of matched items with pagination?

### ISSUE THREAD

**Issue by georgyfarniev** [nextapps-de/flexsearch#71]
Is it possible to know total number of items found, to know how many pages in pagination should be displayed?

**Comment by ts-thomas** [comment]
Yes it is possible. That would disable some important optimization of calculation and complexity, therefore providing an explicit flag (custom search) is recommended.

**Comment by lludol** [comment]
Hello,

I need the same feature.

How can I do that?

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot. Here you need to query with a high limit (e.g. INTEGER_MAX_VALUE) and apply your page by yourself, this also work with server-side rendering. I will add an example to the readme soon.
