### ISSUE TITLE
Not working with React Native

### ISSUE THREAD

**Issue by Haqverdi** [nextapps-de/flexsearch#72]
first thanks for great library, but its not working with react native :(

**Comment by georgyfarniev** [comment]
@Haqverdi, can you please share details about your issue? Code example, error log, etc.

**Comment by Haqverdi** [comment]
Yes, of course, I tried in the environment of nodejs, it works fine there, when I want to use it with the react native, the problem arises in the initialization stage, even when only import is done without use

```
undefined is not an object (evaluating 'v.define')
<unknown>
    flexsearch.min.js:8:41
<unknown>
    flexsearch.min.js:8:170
loadModuleImplementation
    require.js:331:6
<unknown>
    searchTest.js:3
loadModuleImplementation
    require.js:331:6
<unknown>
    Search.js:17
loadModuleImplementation
    require.js:331:6
<unknown>
    Navigation.js:16
loadModuleImplementation
    require.js:331:6
<unknown>
    App.js:3
loadModuleImplementation
    require.js:331:6
<unknown>
    index.js:7
loadModuleImplementation
    require.js:331:6
guardedLoadModule
    require.js:197:45
global code
    <unknown file>:0
```

**Comment by georgyfarniev** [comment]
@Haqverdi not sure if it helps, but have you tried `import * as FlexSearch from ‘flexsearch’`?

**Comment by Haqverdi** [comment]
Yes, I also tried it so it did not work either, but when I downloaded and used a non-minified version I took it from the source so it worked, may be problem with minified version

**Comment by georgyfarniev** [comment]
@Haqverdi then something wrong with custom compile script probably. @ts-thomas may help with this.

**Comment by ts-thomas** [comment]
@georgyfarniev thanks for your help @Haqverdi I will take a look into it

**Comment by gotenxds** [comment]
Just stumbled across here but the issue seems to be that if you 
```import * as FlexSearch from 'flexsearch'```
You will try and import the nodejs version of the library, instead just do this: 
```import FlexSearch from 'flexsearch/dist/flexsearch.min';```

**Comment by jay1337** [comment]
Doesn't work for me.
A workaround is to replace `this` by `window` near the end of file `/dist/flexsearch.min.js`.

**Comment by jay1337** [comment]
One can also rebuild the dist files by changing the browser entry in package.json from
`"browser": "dist/flexsearch.min.js",`
to
`"browser": "flexsearch.js",`

**Comment by saurabhinfoworks** [comment]
any status ?

**Comment by saurabhinfoworks** [comment]
@ts-thomas can we see any fix for this but in near future. I am trying to use flexsearch with npm and similar issue i am facing with minified version of the file. defined is undefined. as soon as i add require, it throws this error in browser.

**Comment by brunohkbx** [comment]
Any updates on this?

**Comment by georgyfarniev** [comment]
@brunohkbx, it looked promising, but seems abandoned now. I already figured out how to work with elasticsearch (for my case)

**Comment by id13** [comment]
To anyone using react-native, and wanting to leverage this library, the “window workaround” still work as of today.
Look at the last characters of the min.js file and replace

`onmessage=W;return K[w][P]}}()),w);` by `onmessage=W;return K[w][P]}}()),window);`

Many thanks to the contributors for this impressive package 😄

**Comment by yaneq** [comment]
This seems to be working with the standard npm package without modifications

typescript:
``` es6
const FlexSearch = require('flexsearch/flexsearch.js')
import { Index } from 'flexsearch'

export const MyComponent = () => {
  const index: Index<string> = FlexSearch.create()
  // [...]
}
```

javascript:
``` es6
const FlexSearch = require('flexsearch/flexsearch.js')

export const MyComponent = () => {
  const index = FlexSearch.create()
  // [...]
}
```

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.

**Comment by yosmanyga** [comment]
This seems to work:

```
// babel.config.js
module.exports = function (api) {
    api.cache(true);
    return {
        presets: [
            [
                'babel-preset-expo',
                {
                    unstable_transformImportMeta: true,
                },
            ]
        ],
        plugins: ...
    };
};
```
