### ISSUE TITLE
Paging with mutltiple fields/boost.

### ISSUE THREAD

**Issue by pauldotknopf** [nextapps-de/flexsearch#75]
## Setup

```javascript
var index = FlexSearch.create({
    doc: {
        id: "url",
        field: [
            "title",
            "content"
        ]
    }
});
```

## Working

**Invoke**:

```javascript
index.search(
    "test",
    {
        page: true,
        limit: 5
    })
```

**Result**:

```javascript
{
  "page": "0",
  "next": "5",
  "result": [
    {
      "title": "Load Testing V. 1.0.1",
      "content": "test",
      "url": "/Project_Management/validations/validation2"
    },
    {
      "title": "Pre Test Inpsection Report",
      "content": "test",
      "url": "/V_and_V/5016-09-F21"
    },
    {
      "title": "Packaging Validaiton Test Report",
      "content": "test",
      "url": "/V_and_V/5016-09-F19"
    },
    {
      "title": "EMC 60601 Test Plan",
      "content": "test",
      "url": "/V_and_V/5016-09-F23"
    },
    {
      "title": "Third Party Testing",
      "content": "test",
      "url": "/3rd_Party_Testing"
    }
  ]
}
```

## Not working

**Invoke**:

```javascript
index.search(
    [
        {
            field: "title",
            query: "test",
            boost: 1
        },
        {
            field: "content",
            query: "test",
            boost: 0.5
        }
    ],
    {
        page: true,
        limit: 5
    }));
```

**Result**:

```javascript
{
  "page": "0",
  "next": null,
  "result": [
  ]
}
```

## Comments

I need to be able to page the results, while also search multiple fields with different ```boost``` values.

**Comment by ts-thomas** [comment]
Boosting fields is actually not supported. Since FlexSearch is using a pre-scored dictionary as its base, it is a bit more difficult to boosting a specific field "on the fly" (when searching). This features is already in progress and hopefully available soon.

Anyway you should get the same results in your example, getting no results actually seems to be a bug.

**Comment by pauldotknopf** [comment]
How do I boost a field during indexing?

**Comment by ts-thomas** [comment]
Unfortunately boosting at all is actually not supported.

**Comment by pauldotknopf** [comment]
Hmm, in the README, it [mentions](https://github.com/nextapps-de/flexsearch#field-search-v070) it's supported. What is this in reference to?

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
