### ISSUE TITLE
JavaScript heap out of memory when exporting index

### ISSUE THREAD

**Issue by ghost** [nextapps-de/flexsearch#85]
Hey Thomas, i'm using your great lib to create indexes for books :) Great documentation and well designed! Thanks for that!

Most of the time it works great without problems, even with node default memory limit of ~1,4 GB. But when i'm exporting really large indexes, i get a `JavaScript heap out of memory` (even with node memory limit of 4 GB). Maybe you can leave me hint or and advice for solving this problem? 

&#x200B;

**Further details**

Bookpages: ~600

Initializing index

    const index = new FlexSearch({
      encode: 'simple',
      tokenize: 'full',
      async: false,
      worker: false,
      cache: false,
    });

Adding text to index:

    for (const page of Object.values(pages)) {
      index.add(page.id, page.text);
    }

Exporting index:

    const exportIndex = index.export();

&#x200B;

Detailed error log:

    \[19:0x557d2a1f3ea0\]   613712 ms: Mark-sweep 4061.3 (4154.4) -> 4061.3 (4155.4) MB, 6482.7 / 0.0 ms  (average mu = 0.116, current mu = 0.003) allocation failure scavenge might not succeed\[19:0x557d2a1f3ea0\]   620227 ms: Mark-sweep 4061.8 (4155.4) -> 4061.8 (4156.4) MB, 6504.6 / 0.0 ms  (average mu = 0.061, current mu = 0.002) allocation failure scavenge might not succeed
    
    <--- JS stacktrace --->
    
    ==== JS stack trace =========================================
    
    Security context: 0x0767d9d9e6e9 <JSObject> 0: builtin exit frame: stringify(this=0x0767d9d91a21 <Object map = 0x19478b3042a9>,0x07a723a026f1 <undefined>,0x07a723a026f1 <undefined>,0x1a3634fa7791 <JSArray\\ \\ \[3\]>,0x0767d9d91a21 <Object map = 0x19478b3042a9>)
    
    1: arguments adaptor frame: 1->3
    
    FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory 2: export \[0x14cf23b5a631\] \\ \\ \[/app/node\_modules/flexsearch/dist/flexsearch.node.js:32\] \\ \\ \[bytecode=0x1788fbe8f8e9 offset=236\](this=0x283799602221...

**Comment by SystemR** [comment]
You need to increase heap size. Run your node app with `--max-old-space-size=8194` to bump it up.

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
