### ISSUE TITLE
Sorting on where()

### ISSUE THREAD

**Issue by jerivas** [nextapps-de/flexsearch#86]
I have a list of items that should be sorted by their title (alphabetical sort) when filtered by an attribute (for example, a category from a finite list), but they should be sorted by relevance when a search is performed.

To perform searches, I'm calling `index.search('some query')` (this already sorts by relevance), and to perform attribute lookups I'm calling `index.where(item => item.animal == 'cat')` (this seems to sort by `item.id`). Is there a way to sort the results returned by `where` by `item.title`?

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
