### ISSUE TITLE
IE11 compatibility (const issue)

### ISSUE THREAD

**Issue by OneCyrus** [nextapps-de/flexsearch#87]
flexsearch has compatibility issue with IE11. currently it produces a `Const must be initialized` error.

Most likely it's because of the const in the for loop. (https://github.com/nextapps-de/flexsearch/blob/3ceb0e9f8a9887bab0f0b57c1a3e41c4fe4c02f3/dist/flexsearch.pre.js#L28)

any chance we get a IE11 compatible version?

**Comment by OneCyrus** [comment]
ok just found that there is already a es5 version in the dist folder. though it's a bit unfortunate that we need to specify this directly. but you can close this if the intention is to use a modern version of the bundle by default.

**Comment by bionicmaster** [comment]
Then, if you're targeting IE11, then you need to import the es5 version? there's some issue or additional problem or functionality not working when doing that? thanks

**Comment by ts-thomas** [comment]
This might be an issue with the closure compiler. I will made some research to this problem. Thanks for the report.

**Comment by Bundas** [comment]
@ts-thomas any progress on this issue?

**Comment by timothy-mccarthyfinch** [comment]
> @ts-thomas any progress on this issue?

do things like this

`import FlexSearch from  'flexsearch/dist/flexsearch.es5.js' `
