### ISSUE TITLE
Sharding serialized exports

### ISSUE THREAD

**Issue by ianloubser** [nextapps-de/flexsearch#92]
I have a project where exporting & importing the generated index happens regularly. But when exporting an index file it can grow quite huge. Is there is a way of sharding the index files in a way that would allow for full usage on a subset of exported index?

Would it be possible to shard the exported index by something like stems if possible? 

Is there a way to achieve this? If possible I'm happy to submit a PR 😬 , just point me in the right direction.

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
