### ISSUE TITLE
Order of Operations for Logical Operators 

### ISSUE THREAD

**Issue by michaelsklepowich** [nextapps-de/flexsearch#93]
I want to be able to provide order of operations in some form to my search method using Boolean logic

The example available in the [readme](https://github.com/nextapps-de/flexsearch#operators) does not provide any context as to how order of operations can be implemented using the data structure.

I want to be able to specify something like:
```js
const booleanLogic = '((1 AND 3) NOT 2)'
const results = index.search([
{
  field: 'field1', 
  query: 'query1', 
  key: 1
}, 
{
  field: 'field2', 
  query: 'query2', 
  key: 2
},
{
  field: 'field3', 
  query: 'query3', 
  key: 3
}], booleanLogic)
// passing the boolean logic as an argument as an example
```
Maybe this functionality already exists in the current implementation, but I can't seem find anything in the docs or the source code.

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x, thanks a lot.
