### ISSUE TITLE
How to get all documents of an index ?

### ISSUE THREAD

**Issue by ScreamZ** [nextapps-de/flexsearch#98]
Hello, @ts-thomas 

I would like to get all documents in a given index to have the i tried search("*") and search("") but i can't get this working...

Any idea ?

Regards

**Comment by ScreamZ** [comment]
Did that, not sure if thats the good/best way to deal with it:

```js
index.where(() => true);
```

What do you think about that ? Got about 1000 smalls JSON docs indexed

**Comment by ts-thomas** [comment]
Please change over to the version >= 0.7.x which gives you access to the "store", thanks a lot.

**Comment by ivandotv** [comment]
`store` has no methods to return all the data.

**Comment by micheljung** [comment]
I'm also interested in this. @ts-thomas can you show how it's possible by accessing the store?
